//! Auto-generated by WASM tuner (stub). When build.rs emits a real table, it will replace this file.
use super::heuristics_router::ChoiceFrac;
pub fn choose_generated(_rows: usize, _cols: usize, _k: usize, _subgroup: bool) -> Option<ChoiceFrac> {
    None
}
