receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: spiraltorch

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
