global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "spiraltorch-runtime"
    static_configs:
      - targets: ["host.docker.internal:9500"]
        labels:
          service: "spiraltorch"
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
