// SPDX-License-Identifier: AGPL-3.0-or-later
// © 2025 Ryo ∴ SpiralArchitect (kishkavsesvit@icloud.com)
// Part of SpiralTorch — Licensed under AGPL-3.0-or-later.
// Unauthorized derivative works or closed redistribution prohibited under AGPL §13.

//! High-order differential structures that weave together homotopies, functors,
//! recursive barycenter flows, and \(\infty\)-categorical towers.
//!
//! The intent is not to mimic classical \(\partial f/\partial x\) operators but
//! to expose the "movement" primitives SpiralTorch already leans on: Z-space
//! barycenters, open-cartesian toposes, and hypergrad tapes.  Each component is
//! intentionally composable so higher layers can trace an activation through the
//! homotopy gate, lift it across a functor, fold in the barycentric energy
//! trail, and finally stitch the result across a tower of curvatures.

use super::measure::{BarycenterIntermediate, ZSpaceBarycenter};
use super::{
    AmegaHypergrad, Layout, MatmulBackend, OpenCartesianTopos, PureResult, Tensor, TensorError,
};

fn checked_f64_to_f32(label: &'static str, value: f64) -> PureResult<f32> {
    if !value.is_finite() || value.abs() > f32::MAX as f64 {
        let value = if value.is_nan() {
            f32::NAN
        } else if value.is_sign_negative() {
            f32::NEG_INFINITY
        } else {
            f32::INFINITY
        };
        return Err(TensorError::NonFiniteValue { label, value });
    }
    Ok(value as f32)
}

fn guard_finite_tensor(label: &'static str, tensor: &Tensor) -> PureResult<()> {
    if !matches!(tensor.layout(), Layout::RowMajor) {
        return Err(TensorError::UnsupportedLayout { label });
    }
    for &value in tensor.data() {
        if !value.is_finite() {
            return Err(TensorError::NonFiniteValue { label, value });
        }
    }
    Ok(())
}

fn guard_probability_tensor(label: &'static str, tensor: &Tensor) -> PureResult<()> {
    guard_finite_tensor(label, tensor)?;
    let mut total = 0.0f64;
    for &value in tensor.data() {
        if value < 0.0 {
            return Err(TensorError::InvalidValue { label });
        }
        total += value as f64;
    }
    if (total - 1.0).abs() > 1.0e-4 {
        return Err(TensorError::InvalidValue { label });
    }
    Ok(())
}

fn stable_matmul(label: &'static str, lhs: &Tensor, rhs: &Tensor) -> PureResult<Tensor> {
    if lhs.shape().1 != rhs.shape().0 {
        return Err(TensorError::ShapeMismatch {
            left: lhs.shape(),
            right: rhs.shape(),
        });
    }
    guard_finite_tensor(label, lhs)?;
    guard_finite_tensor(label, rhs)?;
    match lhs.matmul_with_backend(rhs, MatmulBackend::Auto) {
        Ok(accelerated) => match guard_finite_tensor(label, &accelerated) {
            Ok(()) => return Ok(accelerated),
            Err(TensorError::NonFiniteValue { .. }) => {}
            Err(error) => return Err(error),
        },
        Err(TensorError::NonFiniteValue { .. }) => {}
        Err(error) => return Err(error),
    }
    let (rows, inner) = lhs.shape();
    let cols = rhs.shape().1;
    let volume = rows
        .checked_mul(cols)
        .ok_or(TensorError::InvalidDimensions { rows, cols })?;
    let mut data = Vec::with_capacity(volume);
    for row in 0..rows {
        for col in 0..cols {
            let mut value = 0.0f64;
            for index in 0..inner {
                value +=
                    lhs.data()[row * inner + index] as f64 * rhs.data()[index * cols + col] as f64;
            }
            data.push(checked_f64_to_f32(label, value)?);
        }
    }
    let output = Tensor::from_vec(rows, cols, data)?;
    crate::emit_tensor_op(
        "differential_stable_matmul_fallback",
        &[lhs.shape().0, lhs.shape().1, rhs.shape().0, rhs.shape().1],
        &[rows, cols],
    );
    crate::emit_tensor_op_meta("differential_stable_matmul_fallback", || {
        serde_json::json!({
            "backend": "control_cpu_f64",
            "requested_backend": "auto",
            "kind": "differential_matmul_recovery",
            "reason": "non_finite_accelerated_output",
            "label": label,
            "rows": rows,
            "cols": cols,
            "inner": inner,
        })
    });
    Ok(output)
}

/// Non-commutative differential generated by a homotopy action.
#[derive(Clone, Debug)]
pub struct HomotopyDifferential {
    seed: Tensor,
    generator: Tensor,
    direction: Tensor,
}

impl HomotopyDifferential {
    /// Creates a new homotopy differential. All tensors must share the same shape.
    pub fn new(seed: Tensor, generator: Tensor, direction: Tensor) -> PureResult<Self> {
        let seed_shape = seed.shape();
        if generator.shape() != seed_shape {
            return Err(TensorError::ShapeMismatch {
                left: generator.shape(),
                right: seed_shape,
            });
        }
        if direction.shape() != seed_shape {
            return Err(TensorError::ShapeMismatch {
                left: direction.shape(),
                right: seed_shape,
            });
        }
        guard_finite_tensor("homotopy_seed", &seed)?;
        guard_finite_tensor("homotopy_generator", &generator)?;
        guard_finite_tensor("homotopy_direction", &direction)?;
        Ok(Self {
            seed,
            generator,
            direction,
        })
    }

    /// Returns the seed tensor the flow anchors on.
    pub fn seed(&self) -> &Tensor {
        &self.seed
    }

    /// Returns the direction tensor used for the Hadamard lift.
    pub fn direction(&self) -> &Tensor {
        &self.direction
    }

    /// Returns the generator tensor applied by the flow.
    pub fn generator(&self) -> &Tensor {
        &self.generator
    }

    /// Applies the generator to the provided state.
    pub fn flow_from(&self, state: &Tensor) -> PureResult<Tensor> {
        if state.shape() != self.seed.shape() {
            return Err(TensorError::ShapeMismatch {
                left: state.shape(),
                right: self.seed.shape(),
            });
        }
        guard_finite_tensor("homotopy_state", state)?;
        let mut data = Vec::with_capacity(state.data().len());
        for ((&value, &generator), &direction) in state
            .data()
            .iter()
            .zip(self.generator.data())
            .zip(self.direction.data())
        {
            data.push(checked_f64_to_f32(
                "homotopy_flow",
                value as f64 + generator as f64 * direction as f64,
            )?);
        }
        Tensor::from_vec(state.shape().0, state.shape().1, data)
    }

    /// Applies the generator to the internal seed.
    pub fn flow(&self) -> PureResult<Tensor> {
        self.flow_from(&self.seed)
    }

    /// Applies the generator and rewrites the result through the provided topos.
    pub fn flow_guarded(&self, topos: &OpenCartesianTopos) -> PureResult<Tensor> {
        let mut candidate = self.flow()?;
        topos.saturate_slice(candidate.data_mut());
        topos.guard_tensor("homotopy_flow", &candidate)?;
        Ok(candidate)
    }

    /// Evaluates the commutator with another homotopy differential using the seed.
    pub fn commutator(
        &self,
        other: &HomotopyDifferential,
        topos: Option<&OpenCartesianTopos>,
    ) -> PureResult<Tensor> {
        if self.seed.shape() != other.seed.shape() {
            return Err(TensorError::ShapeMismatch {
                left: self.seed.shape(),
                right: other.seed.shape(),
            });
        }
        let first = self.flow_from(&self.seed)?;
        let forward = other.flow_from(&first)?;
        let second = other.flow_from(&self.seed)?;
        let backward = self.flow_from(&second)?;
        let mut data = Vec::with_capacity(forward.data().len());
        for (&lhs, &rhs) in forward.data().iter().zip(backward.data()) {
            data.push(checked_f64_to_f32(
                "homotopy_commutator",
                lhs as f64 - rhs as f64,
            )?);
        }
        let mut commutator = Tensor::from_vec(self.seed.shape().0, self.seed.shape().1, data)?;
        if let Some(topos) = topos {
            topos.saturate_slice(commutator.data_mut());
            topos.guard_tensor("homotopy_commutator", &commutator)?;
        }
        Ok(commutator)
    }

    /// Squared energy of the generator-direction coupling.
    pub fn directional_energy(&self) -> PureResult<f32> {
        let mut energy = 0.0f64;
        for (&generator, &direction) in self.generator.data().iter().zip(self.direction.data()) {
            let coupled = generator as f64 * direction as f64;
            energy += coupled * coupled;
        }
        checked_f64_to_f32("homotopy_directional_energy", energy)
    }
}

/// Differential acting on functionals through an internal kernel (functor lift).
#[derive(Clone, Debug)]
pub struct FunctorDifferential {
    source: Tensor,
    kernel: Tensor,
    epsilon: f32,
}

impl FunctorDifferential {
    /// Builds a new functor differential. `epsilon` records the positive
    /// perturbation scale even though a linear kernel admits an exact derivative.
    pub fn new(source: Tensor, kernel: Tensor, epsilon: f32) -> PureResult<Self> {
        if !epsilon.is_finite() {
            return Err(TensorError::NonFiniteValue {
                label: "functor_epsilon",
                value: epsilon,
            });
        }
        if epsilon <= 0.0 {
            return Err(TensorError::NonPositiveLearningRate { rate: epsilon });
        }
        if source.shape().1 != kernel.shape().0 {
            return Err(TensorError::ShapeMismatch {
                left: source.shape(),
                right: kernel.shape(),
            });
        }
        guard_finite_tensor("functor_source", &source)?;
        guard_finite_tensor("functor_kernel", &kernel)?;
        Ok(Self {
            source,
            kernel,
            epsilon,
        })
    }

    /// Returns the linearisation step.
    pub fn epsilon(&self) -> f32 {
        self.epsilon
    }

    /// Returns the stored source tensor.
    pub fn source(&self) -> &Tensor {
        &self.source
    }

    /// Returns the linear kernel used by this functor.
    pub fn kernel(&self) -> &Tensor {
        &self.kernel
    }

    /// Applies the functor kernel to the stored source.
    pub fn apply(&self) -> PureResult<Tensor> {
        stable_matmul("functor_apply", &self.source, &self.kernel)
    }

    /// Applies the functor kernel to an arbitrary functional.
    pub fn apply_to(&self, functional: &Tensor) -> PureResult<Tensor> {
        if functional.shape().1 != self.kernel.shape().0 {
            return Err(TensorError::ShapeMismatch {
                left: functional.shape(),
                right: self.kernel.shape(),
            });
        }
        stable_matmul("functor_apply", functional, &self.kernel)
    }

    /// Exact linearisation of the linear kernel along `direction`.
    pub fn linearise(&self, direction: &Tensor) -> PureResult<Tensor> {
        if direction.shape() != self.source.shape() {
            return Err(TensorError::ShapeMismatch {
                left: direction.shape(),
                right: self.source.shape(),
            });
        }
        stable_matmul("functor_linearisation", direction, &self.kernel)
    }
}

/// Recursive differential that follows the barycenter intermediate curve.
#[derive(Clone, Debug)]
pub struct RecursiveDifferential {
    barycenter: ZSpaceBarycenter,
}

impl RecursiveDifferential {
    /// Builds a recursive differential from a barycenter result.
    pub fn from_barycenter(barycenter: &ZSpaceBarycenter) -> PureResult<Self> {
        guard_probability_tensor("recursive_barycenter_density", &barycenter.density)?;
        for (label, value) in [
            ("recursive_barycenter_kl", barycenter.kl_energy),
            ("recursive_barycenter_entropy", barycenter.entropy),
            ("recursive_barycenter_coupling", barycenter.coupling_energy),
            ("recursive_barycenter_objective", barycenter.objective),
            (
                "recursive_barycenter_effective_weight",
                barycenter.effective_weight,
            ),
        ] {
            if !value.is_finite() {
                return Err(TensorError::NonFiniteValue { label, value });
            }
        }
        if barycenter.kl_energy < 0.0
            || barycenter.entropy < 0.0
            || barycenter.coupling_energy < 0.0
        {
            return Err(TensorError::InvalidValue {
                label: "recursive_barycenter_energy",
            });
        }
        if barycenter.effective_weight <= 0.0 {
            return Err(TensorError::DegenerateBarycenter {
                effective_weight: barycenter.effective_weight,
            });
        }
        if barycenter.intermediates.is_empty() {
            return Err(TensorError::EmptyInput(
                "recursive_barycenter_intermediates",
            ));
        }
        let shape = barycenter.density.shape();
        let mut previous_interpolation = f32::NEG_INFINITY;
        let mut previous_objective = f32::INFINITY;
        for stage in &barycenter.intermediates {
            if stage.density.shape() != shape {
                return Err(TensorError::ShapeMismatch {
                    left: shape,
                    right: stage.density.shape(),
                });
            }
            guard_probability_tensor("recursive_intermediate_density", &stage.density)?;
            for (label, value) in [
                ("recursive_interpolation", stage.interpolation),
                ("recursive_intermediate_kl", stage.kl_energy),
                ("recursive_intermediate_entropy", stage.entropy),
                ("recursive_intermediate_objective", stage.objective),
            ] {
                if !value.is_finite() {
                    return Err(TensorError::NonFiniteValue { label, value });
                }
            }
            if !(0.0..=1.0).contains(&stage.interpolation)
                || stage.interpolation < previous_interpolation
            {
                return Err(TensorError::InvalidValue {
                    label: "recursive_interpolation",
                });
            }
            if stage.kl_energy < 0.0 || stage.entropy < 0.0 {
                return Err(TensorError::InvalidValue {
                    label: "recursive_intermediate_energy",
                });
            }
            if stage.objective > previous_objective + 1.0e-4 {
                return Err(TensorError::InvalidValue {
                    label: "recursive_objective_curve",
                });
            }
            previous_interpolation = stage.interpolation;
            previous_objective = stage.objective;
        }
        let last = barycenter
            .intermediates
            .last()
            .ok_or(TensorError::EmptyInput(
                "recursive_barycenter_intermediates",
            ))?;
        for (&actual, &expected) in last.density.data().iter().zip(barycenter.density.data()) {
            if (actual - expected).abs() > 1.0e-4 {
                return Err(TensorError::InvalidValue {
                    label: "recursive_barycenter_endpoint",
                });
            }
        }
        if (last.objective - barycenter.objective).abs() > 1.0e-4 {
            return Err(TensorError::InvalidValue {
                label: "recursive_barycenter_objective_endpoint",
            });
        }
        Ok(Self {
            barycenter: barycenter.clone(),
        })
    }

    /// Returns the barycenter density.
    pub fn density(&self) -> &Tensor {
        &self.barycenter.density
    }

    /// Objective curve sampled along the interpolation path.
    pub fn objective_curve(&self) -> Vec<f32> {
        self.barycenter
            .intermediates
            .iter()
            .map(|stage| stage.objective)
            .collect()
    }

    /// KL energy curve along the interpolation.
    pub fn kl_curve(&self) -> Vec<f32> {
        self.barycenter
            .intermediates
            .iter()
            .map(|stage| stage.kl_energy)
            .collect()
    }

    /// Entropy curve along the interpolation.
    pub fn entropy_curve(&self) -> Vec<f32> {
        self.barycenter
            .intermediates
            .iter()
            .map(|stage| stage.entropy)
            .collect()
    }

    fn curve_tensor(&self, values: &[f32], label: &'static str) -> PureResult<Tensor> {
        if values.is_empty() {
            return Err(TensorError::EmptyInput(label));
        }
        Tensor::from_vec(1, values.len(), values.to_vec())
    }

    /// Tensor form of the objective curve.
    pub fn objective_curve_tensor(&self) -> PureResult<Tensor> {
        let values = self.objective_curve();
        self.curve_tensor(&values, "recursive_objective")
    }

    /// Tensor form of the KL curve.
    pub fn kl_curve_tensor(&self) -> PureResult<Tensor> {
        let values = self.kl_curve();
        self.curve_tensor(&values, "recursive_kl")
    }

    /// Tensor form of the entropy curve.
    pub fn entropy_curve_tensor(&self) -> PureResult<Tensor> {
        let values = self.entropy_curve();
        self.curve_tensor(&values, "recursive_entropy")
    }

    /// Replays the barycenter intermediates into a hypergrad tape.
    pub fn accumulate(&self, hypergrad: &mut AmegaHypergrad) -> PureResult<()> {
        hypergrad.accumulate_barycenter_path(&self.barycenter.intermediates)
    }

    /// Returns a copy of the intermediate densities.
    pub fn intermediates(&self) -> &[BarycenterIntermediate] {
        &self.barycenter.intermediates
    }
}

/// Tower of tensors indexed by curvature levels (\(\infty\)-categorical shadow).
#[derive(Clone, Debug)]
pub struct InfinityDifferential {
    levels: Vec<Tensor>,
    curvatures: Vec<f32>,
}

impl InfinityDifferential {
    /// Builds a differential tower. Empty `curvatures` use unit curvature at every level.
    pub fn new(levels: Vec<Tensor>, curvatures: Vec<f32>) -> PureResult<Self> {
        if levels.is_empty() {
            return Err(TensorError::EmptyInput("infinity_levels"));
        }
        if !curvatures.is_empty() && curvatures.len() != levels.len() {
            return Err(TensorError::DataLength {
                expected: levels.len(),
                got: curvatures.len(),
            });
        }
        let shape = levels[0].shape();
        for level in &levels {
            if level.shape() != shape {
                return Err(TensorError::ShapeMismatch {
                    left: shape,
                    right: level.shape(),
                });
            }
            guard_finite_tensor("infinity_level", level)?;
        }
        for &curvature in &curvatures {
            if !curvature.is_finite() {
                return Err(TensorError::NonFiniteValue {
                    label: "infinity_curvature",
                    value: curvature,
                });
            }
        }
        Ok(Self { levels, curvatures })
    }

    /// Levels participating in the tower.
    pub fn levels(&self) -> &[Tensor] {
        &self.levels
    }

    /// Per-level curvatures.
    pub fn curvatures(&self) -> &[f32] {
        &self.curvatures
    }

    /// Common tensor shape shared by every level.
    pub fn shape(&self) -> (usize, usize) {
        self.levels[0].shape()
    }

    fn curvature_for(&self, idx: usize) -> f32 {
        if self.curvatures.is_empty() {
            1.0
        } else {
            self.curvatures[idx]
        }
    }

    /// Collapses the tower into an averaged tensor.
    pub fn collapse(&self) -> PureResult<Tensor> {
        let (rows, cols) = self.shape();
        let volume = rows
            .checked_mul(cols)
            .ok_or(TensorError::InvalidDimensions { rows, cols })?;
        let mut accum = vec![0.0f64; volume];
        for level in &self.levels {
            for (dest, value) in accum.iter_mut().zip(level.data()) {
                *dest += *value as f64;
            }
        }
        let denominator = self.levels.len() as f64;
        let mut collapsed = Vec::with_capacity(volume);
        for value in accum {
            collapsed.push(checked_f64_to_f32(
                "infinity_collapse",
                value / denominator,
            )?);
        }
        Tensor::from_vec(rows, cols, collapsed)
    }

    /// Hierarchical squared-L2 energy scaled by curvature magnitude.
    pub fn hierarchical_energy_tensor(&self) -> PureResult<Tensor> {
        let mut values = Vec::with_capacity(self.levels.len());
        for (idx, level) in self.levels.iter().enumerate() {
            let curvature = self.curvature_for(idx).abs() as f64;
            let squared_norm = level
                .data()
                .iter()
                .map(|&value| {
                    let value = value as f64;
                    value * value
                })
                .sum::<f64>();
            values.push(checked_f64_to_f32(
                "infinity_hierarchical_energy",
                squared_norm * curvature,
            )?);
        }
        Tensor::from_vec(1, values.len(), values)
    }
}

/// Resonant snapshot produced by [`SpiralDifferential::resonate`].
#[derive(Clone, Debug)]
pub struct DifferentialResonance {
    /// Guarded homotopy flow.
    pub homotopy_flow: Tensor,
    /// Exact functor directional linearisation.
    pub functor_linearisation: Tensor,
    /// Objective values along the validated recursive curve.
    pub recursive_objective: Tensor,
    /// Mean projection of the infinity tower.
    pub infinity_projection: Tensor,
    /// Per-level curvature-scaled squared energy.
    pub infinity_energy: Tensor,
}

/// Unified differential surface combining homotopy, functor, recursive, and \(\infty\) towers.
#[derive(Clone, Debug)]
pub struct SpiralDifferential {
    topos: Option<OpenCartesianTopos>,
    homotopy: HomotopyDifferential,
    functor: FunctorDifferential,
    recursive: RecursiveDifferential,
    infinity: InfinityDifferential,
}

impl SpiralDifferential {
    /// Creates a shape-compatible spiral differential.
    pub fn new(
        topos: Option<OpenCartesianTopos>,
        homotopy: HomotopyDifferential,
        functor: FunctorDifferential,
        recursive: RecursiveDifferential,
        infinity: InfinityDifferential,
    ) -> PureResult<Self> {
        let shape = homotopy.seed().shape();
        for actual in [
            functor.source().shape(),
            recursive.density().shape(),
            infinity.shape(),
        ] {
            if actual != shape {
                return Err(TensorError::ShapeMismatch {
                    left: shape,
                    right: actual,
                });
            }
        }
        let functor_output_shape = (functor.source().shape().0, functor.kernel().shape().1);
        if functor_output_shape != shape {
            return Err(TensorError::ShapeMismatch {
                left: shape,
                right: functor_output_shape,
            });
        }
        if let Some(guard) = &topos {
            guard.guard_tensor("spiral_homotopy_seed", homotopy.seed())?;
            guard.guard_tensor("spiral_homotopy_generator", homotopy.generator())?;
            guard.guard_tensor("spiral_homotopy_direction", homotopy.direction())?;
            guard.guard_tensor("spiral_functor_source", functor.source())?;
            guard.guard_tensor("spiral_functor_kernel", functor.kernel())?;
            guard.guard_tensor("spiral_recursive_density", recursive.density())?;
            for level in infinity.levels() {
                guard.guard_tensor("spiral_infinity_level", level)?;
            }
            if infinity.levels().len() > guard.max_volume() {
                return Err(TensorError::TensorVolumeExceeded {
                    label: "spiral_infinity_energy",
                    volume: infinity.levels().len(),
                    max_volume: guard.max_volume(),
                });
            }
        }
        Ok(Self {
            topos,
            homotopy,
            functor,
            recursive,
            infinity,
        })
    }

    /// Returns the optional guard topos shared by the resonance.
    pub fn topos(&self) -> Option<&OpenCartesianTopos> {
        self.topos.as_ref()
    }

    /// Accessor for the homotopy differential.
    pub fn homotopy(&self) -> &HomotopyDifferential {
        &self.homotopy
    }

    /// Accessor for the functor differential.
    pub fn functor(&self) -> &FunctorDifferential {
        &self.functor
    }

    /// Accessor for the recursive differential.
    pub fn recursive(&self) -> &RecursiveDifferential {
        &self.recursive
    }

    /// Accessor for the \(\infty\)-tower differential.
    pub fn infinity(&self) -> &InfinityDifferential {
        &self.infinity
    }

    /// Runs the full resonance and optionally accumulates the recursive path into a hypergrad.
    pub fn resonate(
        &self,
        hypergrad: Option<&mut AmegaHypergrad>,
    ) -> PureResult<DifferentialResonance> {
        let mut homotopy_flow = self.homotopy.flow()?;
        let mut functor_linear = self.functor.linearise(self.homotopy.direction())?;
        let mut recursive_objective = self.recursive.objective_curve_tensor()?;
        let mut infinity_projection = self.infinity.collapse()?;
        let mut infinity_energy = self.infinity.hierarchical_energy_tensor()?;
        if let Some(topos) = &self.topos {
            topos.saturate_slice(homotopy_flow.data_mut());
            topos.guard_tensor("spiral_resonance_homotopy", &homotopy_flow)?;
            topos.saturate_slice(functor_linear.data_mut());
            topos.guard_tensor("spiral_resonance_functor", &functor_linear)?;
            topos.saturate_slice(recursive_objective.data_mut());
            topos.guard_tensor("spiral_resonance_objective", &recursive_objective)?;
            topos.saturate_slice(infinity_projection.data_mut());
            topos.guard_tensor("spiral_resonance_infinity", &infinity_projection)?;
            topos.saturate_slice(infinity_energy.data_mut());
            topos.guard_tensor("spiral_resonance_energy", &infinity_energy)?;
        }
        if let Some(hypergrad) = hypergrad {
            self.recursive.accumulate(hypergrad)?;
        }
        Ok(DifferentialResonance {
            homotopy_flow,
            functor_linearisation: functor_linear,
            recursive_objective,
            infinity_projection,
            infinity_energy,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[track_caller]
    fn unwrap_ok<T, E: core::fmt::Debug>(result: Result<T, E>) -> T {
        match result {
            Ok(value) => value,
            Err(error) => panic!("expected Ok(..), got Err({error:?})"),
        }
    }

    #[track_caller]
    fn unwrap_err<T, E: core::fmt::Debug>(result: Result<T, E>) -> E {
        match result {
            Ok(_) => panic!("expected Err(..), got Ok(..)"),
            Err(error) => error,
        }
    }

    fn toy_tensor(values: &[f32]) -> Tensor {
        unwrap_ok(Tensor::from_vec(1, values.len(), values.to_vec()))
    }

    fn toy_stage(interpolation: f32, objective: f32, density: &Tensor) -> BarycenterIntermediate {
        BarycenterIntermediate {
            interpolation,
            density: density.clone(),
            kl_energy: interpolation * 0.5,
            entropy: interpolation * 0.25,
            objective,
        }
    }

    fn toy_barycenter(density: &Tensor) -> ZSpaceBarycenter {
        ZSpaceBarycenter {
            density: density.clone(),
            kl_energy: 0.1,
            entropy: 0.3,
            coupling_energy: 0.0,
            objective: 0.4,
            effective_weight: 1.0,
            intermediates: vec![toy_stage(0.2, 0.6, density), toy_stage(0.8, 0.4, density)],
        }
    }

    #[test]
    fn homotopy_validates_finite_ingress_and_uses_a_common_commutator_seed() {
        let error = unwrap_err(HomotopyDifferential::new(
            toy_tensor(&[0.0, f32::NAN]),
            toy_tensor(&[1.0, 1.0]),
            toy_tensor(&[1.0, 1.0]),
        ));
        assert!(matches!(
            error,
            TensorError::NonFiniteValue {
                label: "homotopy_seed",
                ..
            }
        ));

        let first = unwrap_ok(HomotopyDifferential::new(
            toy_tensor(&[1.0, 2.0]),
            toy_tensor(&[0.5, -0.5]),
            toy_tensor(&[2.0, 2.0]),
        ));
        let second = unwrap_ok(HomotopyDifferential::new(
            toy_tensor(&[9.0, 9.0]),
            toy_tensor(&[0.25, 0.75]),
            toy_tensor(&[4.0, -2.0]),
        ));
        let commutator = unwrap_ok(first.commutator(&second, None));
        assert!(commutator.data().iter().all(|value| value.abs() < 1e-6));
    }

    #[test]
    fn homotopy_directional_energy_rejects_unrepresentable_results() {
        let homotopy = unwrap_ok(HomotopyDifferential::new(
            toy_tensor(&[0.0]),
            toy_tensor(&[f32::MAX]),
            toy_tensor(&[2.0]),
        ));
        let error = unwrap_err(homotopy.directional_energy());
        assert!(matches!(
            error,
            TensorError::NonFiniteValue {
                label: "homotopy_directional_energy",
                ..
            }
        ));
    }

    #[test]
    fn functor_uses_stable_matmul_and_exact_linearisation() {
        let cancellation = unwrap_ok(FunctorDifferential::new(
            toy_tensor(&[f32::MAX, f32::MAX]),
            unwrap_ok(Tensor::from_vec(2, 1, vec![2.0, -2.0])),
            0.1,
        ));
        assert_eq!(unwrap_ok(cancellation.apply()).data(), &[0.0]);

        let functor = unwrap_ok(FunctorDifferential::new(
            toy_tensor(&[1.0, 1.0]),
            unwrap_ok(Tensor::from_vec(2, 1, vec![4.0, 5.0])),
            f32::from_bits(1),
        ));
        let linear = unwrap_ok(functor.linearise(&toy_tensor(&[2.0, 3.0])));
        assert_eq!(linear.data(), &[23.0]);
    }

    #[test]
    fn recursive_differential_validates_curve_and_endpoint() {
        let density = toy_tensor(&[0.6, 0.4]);
        let barycenter = toy_barycenter(&density);
        assert!(RecursiveDifferential::from_barycenter(&barycenter).is_ok());

        let mut rising = barycenter.clone();
        rising.intermediates[1].objective = 0.7;
        let error = unwrap_err(RecursiveDifferential::from_barycenter(&rising));
        assert!(matches!(
            error,
            TensorError::InvalidValue {
                label: "recursive_objective_curve"
            }
        ));

        let mut wrong_endpoint = barycenter;
        wrong_endpoint.intermediates[1].density = toy_tensor(&[0.5, 0.5]);
        let error = unwrap_err(RecursiveDifferential::from_barycenter(&wrong_endpoint));
        assert!(matches!(
            error,
            TensorError::InvalidValue {
                label: "recursive_barycenter_endpoint"
            }
        ));
    }

    #[test]
    fn infinity_tower_validates_ingress_and_reduces_in_f64() {
        let error = unwrap_err(InfinityDifferential::new(
            vec![toy_tensor(&[1.0, 2.0]), toy_tensor(&[1.0])],
            vec![],
        ));
        assert!(matches!(error, TensorError::ShapeMismatch { .. }));
        let error = unwrap_err(InfinityDifferential::new(
            vec![toy_tensor(&[1.0])],
            vec![f32::NAN],
        ));
        assert!(matches!(
            error,
            TensorError::NonFiniteValue {
                label: "infinity_curvature",
                ..
            }
        ));

        let tower = unwrap_ok(InfinityDifferential::new(
            vec![toy_tensor(&[f32::MAX]), toy_tensor(&[f32::MAX])],
            vec![],
        ));
        assert_eq!(unwrap_ok(tower.collapse()).data(), &[f32::MAX]);

        let energy = unwrap_ok(InfinityDifferential::new(
            vec![toy_tensor(&[3.0, 4.0])],
            vec![-2.0],
        ));
        assert_eq!(
            unwrap_ok(energy.hierarchical_energy_tensor()).data(),
            &[50.0]
        );
    }

    #[test]
    fn spiral_differential_rejects_cross_layer_shape_and_volume_mismatch() {
        let build_parts = || {
            let seed = toy_tensor(&[0.6, 0.4]);
            let homotopy = unwrap_ok(HomotopyDifferential::new(
                seed.clone(),
                toy_tensor(&[0.1, 0.2]),
                toy_tensor(&[0.3, 0.4]),
            ));
            let functor = unwrap_ok(FunctorDifferential::new(
                seed.clone(),
                unwrap_ok(Tensor::from_vec(2, 2, vec![1.0, 0.0, 0.0, 1.0])),
                0.1,
            ));
            let recursive = unwrap_ok(RecursiveDifferential::from_barycenter(&toy_barycenter(
                &seed,
            )));
            (homotopy, functor, recursive)
        };

        let (homotopy, functor, recursive) = build_parts();
        let infinity = unwrap_ok(InfinityDifferential::new(vec![toy_tensor(&[1.0])], vec![]));
        let error = unwrap_err(SpiralDifferential::new(
            None, homotopy, functor, recursive, infinity,
        ));
        assert!(matches!(error, TensorError::ShapeMismatch { .. }));

        let (homotopy, functor, recursive) = build_parts();
        let infinity = unwrap_ok(InfinityDifferential::new(
            vec![toy_tensor(&[0.6, 0.4])],
            vec![],
        ));
        let topos = unwrap_ok(OpenCartesianTopos::new(-1.0, 1e-5, 10.0, 8, 1));
        let error = unwrap_err(SpiralDifferential::new(
            Some(topos),
            homotopy,
            functor,
            recursive,
            infinity,
        ));
        assert!(matches!(error, TensorError::TensorVolumeExceeded { .. }));
    }

    #[test]
    fn spiral_differential_resonates() {
        let seed = toy_tensor(&[0.5, -0.2]);
        let generator = toy_tensor(&[1.0, -1.0]);
        let direction = toy_tensor(&[0.1, 0.4]);
        let homotopy = unwrap_ok(HomotopyDifferential::new(
            seed.clone(),
            generator,
            direction,
        ));
        let kernel = unwrap_ok(Tensor::from_vec(2, 2, vec![1.0, 0.5, -0.5, 1.5]));
        let functor = unwrap_ok(FunctorDifferential::new(seed.clone(), kernel, 0.01));
        let density = toy_tensor(&[0.6, 0.4]);
        let stage_a = toy_stage(0.2, 0.6, &density);
        let stage_b = toy_stage(0.8, 0.4, &density);
        let barycenter = ZSpaceBarycenter {
            density: density.clone(),
            kl_energy: 0.1,
            entropy: 0.3,
            coupling_energy: 0.0,
            objective: 0.4,
            effective_weight: 1.0,
            intermediates: vec![stage_a, stage_b],
        };
        let recursive = unwrap_ok(RecursiveDifferential::from_barycenter(&barycenter));
        let infinity = unwrap_ok(InfinityDifferential::new(
            vec![density.clone(), density.clone()],
            vec![1.0, 2.0],
        ));
        let topos = unwrap_ok(OpenCartesianTopos::new(-1.0, 1e-4, 10.0, 8, 16));
        let spiral = unwrap_ok(SpiralDifferential::new(
            Some(topos),
            homotopy,
            functor,
            recursive,
            infinity,
        ));
        let resonance = unwrap_ok(spiral.resonate(None));
        assert_eq!(resonance.homotopy_flow.shape(), (1, 2));
        assert_eq!(resonance.functor_linearisation.shape(), (1, 2));
        assert_eq!(resonance.recursive_objective.shape().0, 1);
        assert_eq!(resonance.infinity_projection.shape(), (1, 2));
        assert_eq!(resonance.infinity_energy.shape().0, 1);
    }
}
