version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: monthly
    groups:
      cargo-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      github-actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: pip
    directory: "/bindings/st-py"
    schedule:
      interval: monthly
    groups:
      pip-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
