edition = "2021"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
format_code_in_doc_comments = true
normalize_doc_attributes = true
use_field_init_shorthand = true
wrap_comments = true
newline_style = "Unix"
unstable_features = true
ignore = ["bindings/st-py/src/lib.rs"]
