#!/usr/bin/env python3

from __future__ import annotations

import importlib.util
import json
import subprocess
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "tools" / "run_char_vae_command_bundle.py"


def _load_module():
    spec = importlib.util.spec_from_file_location(
        "run_char_vae_command_bundle",
        SCRIPT,
    )
    module = importlib.util.module_from_spec(spec)
    assert spec is not None and spec.loader is not None
    spec.loader.exec_module(module)
    return module


def _write_json(path: Path, payload: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload), encoding="utf-8")


def _write_script(path: Path, body: str, *, executable: bool = True) -> None:
    path.write_text(
        "\n".join(["#!/usr/bin/env bash", "set -euo pipefail", body, ""]),
        encoding="utf-8",
    )
    if executable:
        path.chmod(path.stat().st_mode | 0o755)


def _runner_command(command_dir: Path) -> str:
    return (
        "env PYTHONNOUSERSITE=1 python3 -P "
        f"{SCRIPT} {command_dir} --write-inspection-report --write-run-report "
        "--append-run-history --write-run-history-report"
    )


def _write_runner_wrapper(path: Path, command_dir: Path) -> None:
    path.write_text(
        "\n".join(
            [
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                "",
                "# Generated by summarize_char_vae_context_chains.py: run_recommended_next",
                "# target_kind: follow_up",
                "# Runs the recommended next action through bundle inspection first.",
                f'exec {_runner_command(command_dir)} "$@"',
                "",
            ]
        ),
        encoding="utf-8",
    )
    path.chmod(path.stat().st_mode | 0o755)


def _chain_path(command_dir: Path) -> str:
    return str(command_dir.parent / "chain" / "chain.json")


def _assert_recommendation_context(
    testcase: unittest.TestCase,
    payload: dict[str, object],
    command_dir: Path,
    *,
    target_kind: str = "follow_up",
) -> None:
    context = payload["recommendation_context"]
    testcase.assertIsInstance(context, dict)
    assert isinstance(context, dict)
    testcase.assertEqual(
        context["schema"],
        "st.llm_char_vae_context.command_bundle_run_recommendation_context.v1",
    )
    testcase.assertEqual(context["action"], "continue_from_accepted")
    testcase.assertEqual(
        context["reason"],
        "accepted champion remains the safest continuation",
    )
    testcase.assertEqual(context["target_kind"], target_kind)
    testcase.assertEqual(context["next_kind"], "follow_up")
    testcase.assertIs(context["accepted_matches_best"], True)
    testcase.assertIs(context["best_requires_review"], False)
    testcase.assertEqual(context["accepted_vs_best_nll_gap"], 0.0)
    testcase.assertEqual(context["chain_sources"], [_chain_path(command_dir)])
    testcase.assertEqual(context["chain_count"], 1)
    testcase.assertEqual(context["attempted_follow_ups"], 1)
    testcase.assertEqual(
        context["follow_up_from_summary_path"],
        _chain_path(command_dir),
    )
    testcase.assertIsNone(context["review_summary_path"])
    testcase.assertEqual(context["champion_source"], _chain_path(command_dir))
    testcase.assertEqual(context["fallback_source"], _chain_path(command_dir))
    testcase.assertEqual(context["follow_up_command_source"], "next_follow_up_command")
    testcase.assertIsNone(context["review_command_source"])
    champion = context["champion"]
    fallback = context["fallback"]
    testcase.assertIsInstance(champion, dict)
    testcase.assertIsInstance(fallback, dict)
    assert isinstance(champion, dict)
    assert isinstance(fallback, dict)
    testcase.assertEqual(champion["config"], "latent@normalize=blocks,scale=0.5")
    testcase.assertEqual(champion["mean_best_nll"], 4.1)
    testcase.assertEqual(champion["summary_path"], _chain_path(command_dir))
    testcase.assertEqual(fallback["config"], "raw@normalize=blocks,scale=1.0")
    testcase.assertEqual(fallback["summary_path"], _chain_path(command_dir))


def _assert_execution_summary(
    testcase: unittest.TestCase,
    payload: dict[str, object],
    command_dir: Path,
) -> None:
    testcase.assertEqual(
        payload["expected_execution_summary_path"],
        str(command_dir / "executed_follow_up" / "summary.json"),
    )
    execution_summary = payload["execution_summary"]
    testcase.assertIsInstance(execution_summary, dict)
    assert isinstance(execution_summary, dict)
    testcase.assertEqual(
        execution_summary["schema"],
        "st.llm_char_vae_context.command_bundle_execution_summary.v1",
    )
    testcase.assertTrue(execution_summary["exists"])
    testcase.assertTrue(execution_summary["valid_json"])
    testcase.assertIsNone(execution_summary["error"])
    testcase.assertEqual(execution_summary["status"], "improved")
    testcase.assertEqual(
        execution_summary["best_config_label"],
        "latent@normalize=blocks,scale=0.5",
    )
    testcase.assertEqual(execution_summary["best_feature"], "latent")
    testcase.assertEqual(execution_summary["mean_best_nll"], 4.0)
    testcase.assertEqual(execution_summary["mean_best_nll_delta_vs_raw"], -0.2)
    testcase.assertEqual(execution_summary["runner_up_feature"], "raw")
    testcase.assertEqual(execution_summary["margin_to_runner_up"], 0.2)
    testcase.assertEqual(execution_summary["follow_up_verdict"], "improved")
    testcase.assertEqual(execution_summary["follow_up_result_verdict"], "improved")
    testcase.assertEqual(execution_summary["follow_up_effective_verdict"], "improved")
    testcase.assertFalse(execution_summary["follow_up_gate_failed"])
    testcase.assertTrue(execution_summary["source_best_feature_retained"])
    testcase.assertEqual(
        execution_summary["guidance_action"],
        "confirm_trajectory_with_fresh_seeds",
    )
    testcase.assertEqual(execution_summary["next_default_new_seeds"], "109,113,127")
    testcase.assertEqual(execution_summary["next_default_new_seed_count"], 3)
    testcase.assertTrue(execution_summary["guided_next_enabled"])
    testcase.assertEqual(execution_summary["used_seed_history"], [7, 101, 103, 107])
    next_command = execution_summary["next_command"]
    testcase.assertIsInstance(next_command, dict)
    assert isinstance(next_command, dict)
    testcase.assertEqual(
        next_command["schema"],
        "st.llm_char_vae_context.command_bundle_execution_next_command.v1",
    )
    testcase.assertTrue(next_command["available"])
    testcase.assertEqual(next_command["source"], "guided_next_follow_up_command")
    testcase.assertTrue(next_command["enabled"])
    testcase.assertEqual(
        next_command["guidance_action"],
        "confirm_trajectory_with_fresh_seeds",
    )
    testcase.assertEqual(next_command["default_new_seeds"], "109,113,127")
    testcase.assertEqual(next_command["default_new_seed_count"], 3)
    testcase.assertEqual(
        next_command["default_run_dir"],
        str(command_dir / "executed_follow_up" / "next"),
    )
    testcase.assertEqual(
        next_command["script_path"],
        str(command_dir / "executed_follow_up" / "guided_next_follow_up_command.sh"),
    )
    testcase.assertIn("NEW_SEEDS=109,113,127", next_command["script_usage"])


def _write_bundle(
    root: Path,
    *,
    non_executable_follow_up: bool = False,
    include_review: bool = False,
    include_runner_wrapper: bool = False,
) -> Path:
    command_dir = root / "commands"
    command_dir.mkdir(parents=True, exist_ok=True)
    chain = root / "chain" / "chain.json"
    _write_json(chain, {"schema": "st.llm_char_vae_context.chain.v1"})

    comparison_json = command_dir / "comparison.json"
    comparison_markdown = command_dir / "comparison.md"
    _write_json(comparison_json, {"schema": "comparison"})
    comparison_markdown.write_text("# comparison\n", encoding="utf-8")
    (command_dir / "README.md").write_text("# commands\n", encoding="utf-8")

    next_script = command_dir / "recommended_next.sh"
    follow_up_script = command_dir / "recommended_follow_up.sh"
    review_script = command_dir / "recommended_review.sh"
    runner_script = command_dir / "run_recommended_next.sh"
    execution_dir = command_dir / "executed_follow_up"
    execution_summary_body = "\n".join(
        [
            'mkdir -p "executed_follow_up"',
            'cat > "executed_follow_up/summary.json" <<\'JSON\'',
            json.dumps(
                {
                    "schema": "st.modelzoo.run.v1",
                    "status": "improved",
                    "best_feature": "latent",
                    "best_config": {
                        "best_feature": "latent",
                        "feature_normalize": "blocks",
                        "hybrid_latent_scale": 0.5,
                        "mean_best_nll": 4.0,
                        "mean_best_nll_delta_vs_raw": -0.2,
                        "runner_up_feature": "raw",
                        "margin_to_runner_up": 0.2,
                        "combined_runner_up_margin_stderr": 0.05,
                        "runner_up_within_uncertainty": False,
                    },
                    "follow_up_result": {
                        "verdict": "improved",
                        "source_best_feature_retained": True,
                        "mean_best_nll_delta_vs_source": -0.1,
                    },
                    "follow_up_gate": {
                        "effective_verdict": "improved",
                        "failed": False,
                    },
                    "follow_up_guidance": {
                        "action": "confirm_trajectory_with_fresh_seeds",
                        "unsafe_promotion": False,
                    },
                    "follow_up_trajectory": {
                        "trajectory_action": "confirm_trajectory_with_fresh_seeds",
                        "trajectory_verdict": "improved",
                    },
                    "next_follow_up_command": {
                        "default_new_seeds": "109,113,127",
                        "default_new_seed_count": 3,
                        "default_follow_up_from": str(execution_dir / "summary.json"),
                        "default_run_dir": str(execution_dir / "next"),
                        "script_path": str(execution_dir / "next_follow_up_command.sh"),
                        "script_usage": (
                            f"NEW_SEEDS=109,113,127 bash "
                            f"{execution_dir / 'next_follow_up_command.sh'}"
                        ),
                        "used_seed_history": [7, 101, 103, 107],
                        "seed_confirmation_policy": {
                            "reason": "default fresh-seed confirmation",
                            "uncertainty_tie_seed_boost": False,
                        },
                    },
                    "guided_next_follow_up_command": {
                        "enabled": True,
                        "guidance_action": "confirm_trajectory_with_fresh_seeds",
                        "trajectory_action": "confirm_trajectory_with_fresh_seeds",
                        "verdict": "improved",
                        "gate_failed": False,
                        "script_path": str(
                            execution_dir / "guided_next_follow_up_command.sh"
                        ),
                        "script_usage": (
                            f"NEW_SEEDS=109,113,127 bash "
                            f"{execution_dir / 'guided_next_follow_up_command.sh'}"
                        ),
                        "default_follow_up_from": str(execution_dir / "summary.json"),
                        "default_run_dir": str(execution_dir / "next"),
                        "default_new_seeds": "109,113,127",
                        "default_new_seed_count": 3,
                        "used_seed_history": [7, 101, 103, 107],
                        "seed_confirmation_policy": {
                            "reason": "default fresh-seed confirmation",
                            "uncertainty_tie_seed_boost": False,
                        },
                    },
                }
            ),
            "JSON",
            f'cat > "{execution_dir / "guided_next_follow_up_command.sh"}" <<\'SH\'',
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            f'mkdir -p "{execution_dir / "next"}"',
            'printf "execution-next cwd=%s\\n" "$(pwd)" | tee execution_next.out',
            f'cat > "{execution_dir / "next" / "summary.json"}" <<\'JSON\'',
            json.dumps(
                {
                    "schema": "st.modelzoo.run.v1",
                    "status": "improved",
                    "best_feature": "latent",
                    "best_config": {
                        "best_feature": "latent",
                        "feature_normalize": "blocks",
                        "hybrid_latent_scale": 0.5,
                        "mean_best_nll": 3.8,
                        "mean_best_nll_delta_vs_raw": -0.4,
                        "runner_up_feature": "raw",
                        "margin_to_runner_up": 0.4,
                        "combined_runner_up_margin_stderr": 0.05,
                        "runner_up_within_uncertainty": False,
                    },
                    "follow_up_result": {
                        "verdict": "improved",
                        "source_best_feature_retained": True,
                        "mean_best_nll_delta_vs_source": -0.2,
                    },
                    "follow_up_gate": {
                        "effective_verdict": "improved",
                        "failed": False,
                    },
                    "follow_up_guidance": {
                        "action": "promote_and_broaden_after_streak",
                        "unsafe_promotion": False,
                    },
                    "follow_up_trajectory": {
                        "trajectory_action": "confirm_trajectory_with_fresh_seeds",
                        "trajectory_verdict": "improved",
                    },
                }
            ),
            "JSON",
            "SH",
            f'chmod +x "{execution_dir / "guided_next_follow_up_command.sh"}"',
        ]
    )
    _write_script(
        next_script,
        "\n".join(
            [
                'printf "next cwd=%s\\n" "$(pwd)" | tee runner.out',
                execution_summary_body,
            ]
        ),
    )
    _write_script(
        follow_up_script,
        "\n".join(
            [
                'printf "follow cwd=%s\\n" "$(pwd)" | tee runner.out',
                execution_summary_body,
            ]
        ),
        executable=not non_executable_follow_up,
    )
    if include_review:
        _write_script(
            review_script,
            'printf "review cwd=%s\\n" "$(pwd)" | tee runner.out',
        )
    if include_runner_wrapper:
        _write_runner_wrapper(runner_script, command_dir)

    _write_json(
        command_dir / "recommendation.json",
        {
            "schema": "st.llm_char_vae_context.chain_command_manifest.v1",
            "comparison": {
                "schema": "st.llm_char_vae_context.chain_comparison.v1",
                "chain_sources": [str(chain)],
            },
            "aggregate": {
                "chain_count": 1,
                "attempted_follow_ups": 1,
            },
            "selection": {
                "accepted_matches_best": True,
                "best_requires_review": False,
                "accepted_vs_best_nll_gap": 0.0,
            },
            "recommendation": {
                "action": "continue_from_accepted",
                "reason": "accepted champion remains the safest continuation",
                "follow_up_from_summary_path": str(chain),
                "review_summary_path": None,
                "champion_source": str(chain),
                "champion": {
                    "config": "latent@normalize=blocks,scale=0.5",
                    "mean_best_nll": 4.1,
                    "step": 1,
                    "summary_path": str(chain),
                },
                "fallback_source": str(chain),
                "fallback": {
                    "config": "raw@normalize=blocks,scale=1.0",
                    "mean_best_nll": 4.2,
                    "step": 0,
                    "summary_path": str(chain),
                },
                "follow_up_command": {
                    "command_source": "next_follow_up_command",
                    "source_summary_path": str(chain),
                    "default_run_dir": str(execution_dir),
                },
                "review_command": None,
            },
            "command_scripts": {
                "schema": "st.llm_char_vae_context.chain_command_scripts.v1",
                "directory": str(command_dir),
                "next_path": str(next_script),
                "next_kind": "follow_up",
                "follow_up_path": str(follow_up_script),
                "review_path": str(review_script) if include_review else None,
                "written_count": 3 if include_review else 2,
                "comparison_json_path": str(comparison_json),
                "comparison_markdown_path": str(comparison_markdown),
                "runner_command": _runner_command(command_dir)
                if include_runner_wrapper
                else None,
                "runner_path": str(runner_script) if include_runner_wrapper else None,
                "inspection_json_path": str(command_dir / "inspection.json"),
                "inspection_markdown_path": str(command_dir / "inspection.md"),
                "run_json_path": str(command_dir / "run.json"),
                "run_markdown_path": str(command_dir / "run.md"),
                "run_history_jsonl_path": str(command_dir / "run_history.jsonl"),
                "run_history_markdown_path": str(command_dir / "run_history.md"),
                "run_history_summary_path": str(
                    command_dir / "run_history_summary.json"
                ),
                "execution_cwd": str(command_dir),
                "readme_path": str(command_dir / "README.md"),
            },
        },
    )
    return command_dir


class RunCharVaeCommandBundleTests(unittest.TestCase):
    def test_execution_evidence_status_marks_mixed_review_signal(self) -> None:
        mod = _load_module()
        fields = mod._execution_evidence_fields(
            {
                "exists": True,
                "valid_json": True,
                "status": "improved",
                "follow_up_result_verdict": "regressed",
                "follow_up_verdict": "regressed",
                "follow_up_effective_verdict": "improved",
                "follow_up_gate_failed": False,
                "guidance_action": "review_feature_swap_before_promotion",
            }
        )

        self.assertEqual(fields["execution_evidence_status"], "needs_review")
        self.assertEqual(
            fields["execution_evidence_reason"],
            "review_feature_swap_before_promotion",
        )
        self.assertFalse(fields["execution_evidence_should_continue"])
        self.assertTrue(fields["execution_evidence_mixed_signal"])

    def test_history_markdown_surfaces_problem_signals(self) -> None:
        mod = _load_module()
        events = [
            {
                "target": "next",
                "target_kind": "follow_up",
                "dry_run": False,
                "executed": True,
                "returncode": 0,
                "finished_at": "2026-06-28T00:00:00.000Z",
                "recommendation_context": {
                    "action": "continue_from_accepted",
                    "champion": {"config": "latent@scale=0.5"},
                },
                "execution_summary": {
                    "follow_up_verdict": "regressed",
                    "follow_up_effective_verdict": "improved",
                    "guidance_action": "review_feature_swap_before_promotion",
                },
                "execution_evidence_status": "needs_review",
                "execution_evidence_reason": "review_feature_swap_before_promotion",
                "execution_evidence_should_continue": False,
                "execution_evidence_mixed_signal": True,
            },
            {
                "target": "next",
                "target_kind": "review",
                "dry_run": False,
                "executed": False,
                "returncode": 1,
                "error": "command bundle did not pass the requested inspection gate",
                "missing_required": ["recommended_review.sh"],
                "recommendation_context": {
                    "action": "review_absolute_best",
                    "champion": {"config": "raw_latent@scale=4.0"},
                },
            },
            {
                "target": "next",
                "target_kind": "review",
                "dry_run": False,
                "executed": False,
                "returncode": 1,
                "error": "command bundle did not pass the requested inspection gate",
                "missing_required": ["recommended_review.sh"],
                "recommendation_context": {
                    "action": "review_absolute_best",
                    "champion": {"config": "raw_latent@scale=4.0"},
                },
            },
        ]
        markdown = mod.render_history_markdown(
            events,
            history_jsonl_path=Path("/tmp/run_history.jsonl"),
        )
        summary = mod.summarize_history_events(
            events,
            history_jsonl_path=Path("/tmp/run_history.jsonl"),
        )

        self.assertEqual(
            summary["schema"],
            "st.llm_char_vae_context.command_bundle_run_history_summary.v1",
        )
        self.assertEqual(summary["history_jsonl_path"], "/tmp/run_history.jsonl")
        self.assertEqual(summary["total_runs"], 3)
        self.assertEqual(summary["success_count"], 1)
        self.assertEqual(summary["failure_count"], 2)
        self.assertEqual(summary["latest"]["status"], "blocked")
        self.assertEqual(summary["latest"]["target_kind"], "review")
        self.assertEqual(
            summary["signals"]["status_counts"],
            {"blocked": 2, "ok": 1},
        )
        self.assertEqual(
            summary["signals"]["target_kind_counts"],
            {"follow_up": 1, "review": 2},
        )
        self.assertEqual(
            summary["signals"]["recommendation_action_counts"],
            {"continue_from_accepted": 1, "review_absolute_best": 2},
        )
        self.assertEqual(
            summary["signals"]["current_status_streak"],
            {"status": "blocked", "count": 2},
        )
        self.assertEqual(
            summary["signals"]["execution_evidence_status_counts"],
            {"needs_review": 1},
        )
        self.assertEqual(summary["signals"]["latest_executed"]["status"], "ok")
        self.assertEqual(
            summary["signals"]["latest_executed"]["execution_evidence_status"],
            "needs_review",
        )
        self.assertTrue(
            summary["signals"]["latest_executed"]["execution_evidence_mixed_signal"]
        )
        self.assertEqual(
            summary["signals"]["latest_executed"]["recommendation_action"],
            "continue_from_accepted",
        )
        self.assertEqual(
            summary["signals"]["latest_executed"]["champion_config"],
            "latent@scale=0.5",
        )
        self.assertEqual(summary["signals"]["last_problem"]["status"], "blocked")
        self.assertEqual(
            summary["signals"]["last_problem"]["missing_required"],
            ["recommended_review.sh"],
        )
        self.assertIn("status_counts: blocked:2, ok:1", markdown)
        self.assertIn("target_kind_counts: follow_up:1, review:2", markdown)
        self.assertIn(
            "recommendation_action_counts: continue_from_accepted:1, "
            "review_absolute_best:2",
            markdown,
        )
        self.assertIn("current_status_streak: blocked:2", markdown)
        self.assertIn("execution_evidence_status_counts: needs_review:1", markdown)
        self.assertIn("latest_executed_status: ok", markdown)
        self.assertIn("latest_executed_execution_evidence_status: needs_review", markdown)
        self.assertIn(
            "latest_executed_execution_evidence_reason: "
            "review_feature_swap_before_promotion",
            markdown,
        )
        self.assertIn("latest_executed_execution_evidence_mixed_signal: yes", markdown)
        self.assertIn("latest_executed_action: continue_from_accepted", markdown)
        self.assertIn("latest_executed_champion_config: latent@scale=0.5", markdown)
        self.assertIn("last_problem_status: blocked", markdown)
        self.assertIn(
            "last_problem_error: command bundle did not pass the requested "
            "inspection gate",
            markdown,
        )
        self.assertIn("last_problem_missing_required: recommended_review.sh", markdown)

    def test_cli_dry_run_reports_next_without_running(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--dry-run", "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            payload = json.loads(result.stdout)
            runner_out_exists = (command_dir / "runner.out").exists()

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertTrue(payload["dry_run"])
        self.assertEqual(payload["target"], "next")
        self.assertEqual(payload["target_kind"], "follow_up")
        self.assertEqual(payload["script_key"], "next_path")
        self.assertEqual(payload["target_script_key"], "follow_up_path")
        self.assertEqual(
            payload["target_script_path"],
            str(command_dir / "recommended_follow_up.sh"),
        )
        _assert_recommendation_context(self, payload, command_dir)
        self.assertTrue(payload["strict_ready"])
        self.assertFalse(payload["executed"])
        self.assertIsNotNone(payload["started_at"])
        self.assertIsNotNone(payload["finished_at"])
        self.assertIsNone(payload["run_history_jsonl_path"])
        self.assertIsNone(payload["run_history_markdown_path"])
        self.assertIsNone(payload["run_history_summary_path"])
        self.assertGreaterEqual(payload["duration_seconds"], 0.0)
        self.assertEqual(payload["execution_cwd"], str(command_dir.resolve()))
        self.assertEqual(
            payload["command_argv"],
            ["bash", str(command_dir / "recommended_next.sh")],
        )
        self.assertEqual(
            payload["expected_execution_summary_path"],
            str(command_dir / "executed_follow_up" / "summary.json"),
        )
        self.assertIsNone(payload["execution_summary"])
        self.assertFalse(runner_out_exists)

    def test_cli_runs_next_after_strict_inspection(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            payload = json.loads(result.stdout)
            runner_out = (command_dir / "runner.out").read_text(encoding="utf-8")

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(payload["returncode"], 0)
        self.assertEqual(payload["target"], "next")
        self.assertEqual(payload["target_kind"], "follow_up")
        self.assertEqual(payload["target_script_key"], "follow_up_path")
        self.assertEqual(
            payload["target_script_path"],
            str(command_dir / "recommended_follow_up.sh"),
        )
        _assert_recommendation_context(self, payload, command_dir)
        self.assertIsNone(payload["run_history_jsonl_path"])
        self.assertIsNone(payload["run_history_markdown_path"])
        self.assertIsNone(payload["run_history_summary_path"])
        self.assertTrue(payload["executed"])
        self.assertGreaterEqual(payload["duration_seconds"], 0.0)
        self.assertIn("next cwd=", payload["stdout"])
        self.assertIn(str(command_dir), runner_out)
        _assert_execution_summary(self, payload, command_dir)

    def test_cli_runs_execution_next_from_previous_run_report(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            first = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--write-run-report",
                    "--json",
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            dry = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--target",
                    "execution-next",
                    "--dry-run",
                    "--write-run-report",
                    "--json",
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            executed = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--target",
                    "execution-next",
                    "--write-run-report",
                    "--append-run-history",
                    "--write-run-history-report",
                    "--json",
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            first_payload = json.loads(first.stdout)
            dry_payload = json.loads(dry.stdout)
            executed_payload = json.loads(executed.stdout)
            run_report = json.loads(
                (command_dir / "run.json").read_text(encoding="utf-8")
            )
            history_summary = json.loads(
                (command_dir / "run_history_summary.json").read_text(encoding="utf-8")
            )

        self.assertEqual(first.returncode, 0, first.stderr)
        self.assertEqual(dry.returncode, 0, dry.stderr)
        self.assertEqual(executed.returncode, 0, executed.stderr)
        _assert_execution_summary(self, first_payload, command_dir)
        self.assertEqual(dry_payload["target"], "execution-next")
        self.assertEqual(dry_payload["target_kind"], "execution_next")
        self.assertEqual(
            dry_payload["selected_execution_next_command"]["source"],
            "guided_next_follow_up_command",
        )
        self.assertEqual(
            dry_payload["selected_execution_next_command"]["default_new_seeds"],
            "109,113,127",
        )
        self.assertEqual(
            dry_payload["script_key"],
            "execution_summary.next_command.script_path",
        )
        self.assertEqual(
            dry_payload["script_path"],
            str(command_dir / "executed_follow_up" / "guided_next_follow_up_command.sh"),
        )
        self.assertEqual(
            dry_payload["expected_execution_summary_path"],
            str(command_dir / "executed_follow_up" / "next" / "summary.json"),
        )
        self.assertEqual(dry_payload["execution_cwd"], str(command_dir))
        self.assertIsNone(dry_payload["execution_summary"])
        self.assertEqual(executed_payload["target"], "execution-next")
        self.assertEqual(executed_payload["target_kind"], "execution_next")
        self.assertEqual(executed_payload["returncode"], 0)
        self.assertIn("execution-next cwd=", executed_payload["stdout"])
        self.assertEqual(
            executed_payload["execution_summary"]["summary_path"],
            str(command_dir / "executed_follow_up" / "next" / "summary.json"),
        )
        self.assertEqual(executed_payload["execution_summary"]["mean_best_nll"], 3.8)
        self.assertEqual(
            executed_payload["execution_summary"]["guidance_action"],
            "promote_and_broaden_after_streak",
        )
        self.assertEqual(run_report["target"], "execution-next")
        self.assertEqual(run_report["target_kind"], "execution_next")
        self.assertEqual(history_summary["latest"]["target_kind"], "execution_next")
        self.assertEqual(
            history_summary["latest"]["execution_guidance_action"],
            "promote_and_broaden_after_streak",
        )

    def test_cli_recovers_execution_next_from_history_when_run_report_is_stale(
        self,
    ) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            first = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--write-run-report",
                    "--append-run-history",
                    "--json",
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            stale_report = {
                "schema": "st.llm_char_vae_context.command_bundle_run.v1",
                "target": "execution-next",
                "target_kind": "execution_next",
                "dry_run": True,
                "executed": False,
                "returncode": 0,
                "execution_summary": None,
            }
            (command_dir / "run.json").write_text(
                json.dumps(stale_report, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            executed = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--target",
                    "execution-next",
                    "--write-run-report",
                    "--json",
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            first_payload = json.loads(first.stdout)
            executed_payload = json.loads(executed.stdout)

        self.assertEqual(first.returncode, 0, first.stderr)
        self.assertEqual(executed.returncode, 0, executed.stderr)
        _assert_execution_summary(self, first_payload, command_dir)
        self.assertEqual(
            executed_payload["selected_execution_next_command"]["script_path"],
            str(command_dir / "executed_follow_up" / "guided_next_follow_up_command.sh"),
        )
        self.assertEqual(executed_payload["returncode"], 0)
        self.assertIn("execution-next cwd=", executed_payload["stdout"])
        self.assertEqual(
            executed_payload["execution_summary"]["summary_path"],
            str(command_dir / "executed_follow_up" / "next" / "summary.json"),
        )

    def test_cli_blocks_when_strict_inspection_fails(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp), non_executable_follow_up=True)
            strict = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            strict_payload = json.loads(strict.stdout)
            relaxed = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--no-strict",
                    "--json",
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            relaxed_payload = json.loads(relaxed.stdout)

        self.assertEqual(strict.returncode, 1)
        self.assertFalse(strict_payload["strict_ready"])
        self.assertFalse(strict_payload["executed"])
        self.assertEqual(strict_payload["target_kind"], "follow_up")
        self.assertEqual(strict_payload["target_script_key"], "follow_up_path")
        _assert_recommendation_context(self, strict_payload, command_dir)
        self.assertIsNone(strict_payload["run_history_jsonl_path"])
        self.assertIsNone(strict_payload["run_history_markdown_path"])
        self.assertIsNone(strict_payload["run_history_summary_path"])
        self.assertGreaterEqual(strict_payload["duration_seconds"], 0.0)
        self.assertIn("follow_up_script", strict_payload["missing_optional"])
        self.assertEqual(
            strict_payload["error"],
            "command bundle did not pass the requested inspection gate",
        )
        self.assertEqual(relaxed.returncode, 0, relaxed.stderr)
        self.assertEqual(relaxed_payload["returncode"], 0)

    def test_cli_history_report_only_bypasses_execution_gate(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp), non_executable_follow_up=True)
            result = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--history-report-only",
                    "--json",
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            payload = json.loads(result.stdout)
            history_summary_path = command_dir / "run_history_summary.json"
            history_summary = json.loads(
                history_summary_path.read_text(encoding="utf-8")
            )

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertFalse(payload["strict_ready"])
        self.assertFalse(payload["executed"])
        self.assertTrue(payload["history_report_only"])
        self.assertFalse((command_dir / "runner.out").exists())
        self.assertEqual(payload["run_history_summary"]["total_runs"], 0)
        self.assertEqual(history_summary["total_runs"], 0)

    def test_cli_rejects_history_report_only_with_append(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            result = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--history-report-only",
                    "--append-run-history",
                    "--json",
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

        self.assertEqual(result.returncode, 2)
        self.assertIn(
            "--history-report-only cannot be combined with --append-run-history",
            result.stderr,
        )

    def test_cli_reports_missing_target_script(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            result = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--target",
                    "review",
                    "--json",
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            payload = json.loads(result.stdout)

        self.assertEqual(result.returncode, 1)
        self.assertEqual(payload["target_kind"], "review")
        self.assertEqual(payload["script_key"], "review_path")
        self.assertEqual(payload["target_script_key"], "review_path")
        self.assertIsNone(payload["target_script_path"])
        _assert_recommendation_context(
            self,
            payload,
            command_dir,
            target_kind="review",
        )
        self.assertIsNone(payload["run_history_jsonl_path"])
        self.assertIsNone(payload["run_history_markdown_path"])
        self.assertIsNone(payload["run_history_summary_path"])
        self.assertFalse(payload["executed"])
        self.assertEqual(payload["error"], "manifest does not declare review_path")

    def test_cli_runs_review_target_with_resolved_kind(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp), include_review=True)
            result = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--target",
                    "review",
                    "--json",
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            payload = json.loads(result.stdout)

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(payload["target"], "review")
        self.assertEqual(payload["target_kind"], "review")
        self.assertEqual(payload["script_key"], "review_path")
        self.assertEqual(payload["target_script_key"], "review_path")
        self.assertEqual(
            payload["target_script_path"],
            str(command_dir / "recommended_review.sh"),
        )
        _assert_recommendation_context(
            self,
            payload,
            command_dir,
            target_kind="review",
        )
        self.assertIsNone(payload["run_history_jsonl_path"])
        self.assertIsNone(payload["run_history_markdown_path"])
        self.assertIsNone(payload["run_history_summary_path"])
        self.assertEqual(
            payload["command_argv"],
            ["bash", str(command_dir / "recommended_review.sh")],
        )
        self.assertTrue(payload["executed"])
        self.assertIn("review cwd=", payload["stdout"])

    def test_cli_writes_inspection_report_before_running(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            result = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--write-inspection-report",
                    "--write-run-report",
                    "--json",
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            payload = json.loads(result.stdout)
            markdown_exists = (command_dir / "inspection.md").exists()
            run_markdown_exists = (command_dir / "run.md").exists()
            inspection = json.loads(
                (command_dir / "inspection.json").read_text(encoding="utf-8")
            )
            run_report = json.loads(
                (command_dir / "run.json").read_text(encoding="utf-8")
            )
            inspection_outputs = {
                item["label"]: item for item in inspection["declared_outputs"]
            }
            payload_outputs = {
                item["label"]: item
                for item in payload["inspection"]["declared_outputs"]
            }
            run_report_outputs = {
                item["label"]: item
                for item in run_report["inspection"]["declared_outputs"]
            }

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertTrue(markdown_exists)
        self.assertTrue(run_markdown_exists)
        self.assertTrue(inspection["strict_ready"])
        self.assertTrue(inspection_outputs["run_json"]["exists"])
        self.assertTrue(inspection_outputs["run_markdown"]["exists"])
        self.assertTrue(payload_outputs["run_json"]["exists"])
        self.assertTrue(payload_outputs["run_markdown"]["exists"])
        self.assertTrue(run_report_outputs["run_json"]["exists"])
        self.assertTrue(run_report_outputs["run_markdown"]["exists"])
        self.assertEqual(
            payload["inspection"]["inspection_json_path"],
            str(command_dir / "inspection.json"),
        )
        self.assertEqual(payload["run_json_path"], str(command_dir / "run.json"))
        self.assertEqual(payload["target_kind"], "follow_up")
        _assert_recommendation_context(self, payload, command_dir)
        self.assertTrue(payload["executed"])
        self.assertIsNotNone(payload["started_at"])
        self.assertEqual(run_report["returncode"], 0)
        self.assertEqual(run_report["target_kind"], "follow_up")
        _assert_recommendation_context(self, run_report, command_dir)
        self.assertEqual(run_report["target_script_key"], "follow_up_path")
        self.assertEqual(
            run_report["target_script_path"],
            str(command_dir / "recommended_follow_up.sh"),
        )
        self.assertTrue(run_report["executed"])
        self.assertGreaterEqual(run_report["duration_seconds"], 0.0)
        self.assertEqual(run_report["execution_cwd"], str(command_dir.resolve()))
        self.assertEqual(run_report["run_markdown_path"], str(command_dir / "run.md"))
        self.assertIsNone(run_report["run_history_jsonl_path"])
        self.assertIsNone(run_report["run_history_markdown_path"])
        self.assertIsNone(run_report["run_history_summary_path"])
        _assert_execution_summary(self, payload, command_dir)
        _assert_execution_summary(self, run_report, command_dir)

    def test_cli_surfaces_runner_wrapper_status_in_run_outputs(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp), include_runner_wrapper=True)
            result = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--write-run-report",
                    "--append-run-history",
                    "--write-run-history-report",
                    "--json",
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            payload = json.loads(result.stdout)
            run_report = json.loads(
                (command_dir / "run.json").read_text(encoding="utf-8")
            )
            run_markdown = (command_dir / "run.md").read_text(encoding="utf-8")
            history_events = [
                json.loads(line)
                for line in (command_dir / "run_history.jsonl")
                .read_text(encoding="utf-8")
                .splitlines()
            ]
            history_summary = json.loads(
                (command_dir / "run_history_summary.json").read_text(encoding="utf-8")
            )
            history_markdown = (command_dir / "run_history.md").read_text(
                encoding="utf-8"
            )

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertTrue(payload["runner_wrapper_ok"])
        self.assertTrue(payload["runner_wrapper_executes_runner_command"])
        self.assertTrue(payload["runner_wrapper_forwards_arguments"])
        _assert_execution_summary(self, payload, command_dir)
        self.assertEqual(
            payload["runner_wrapper_status"],
            payload["inspection"]["runner_wrapper_status"],
        )
        self.assertTrue(run_report["runner_wrapper_ok"])
        self.assertTrue(run_report["runner_wrapper_executes_runner_command"])
        self.assertTrue(run_report["runner_wrapper_forwards_arguments"])
        _assert_execution_summary(self, run_report, command_dir)
        self.assertEqual(
            run_report["runner_wrapper_status"],
            run_report["inspection"]["runner_wrapper_status"],
        )
        self.assertEqual(len(history_events), 1)
        self.assertTrue(history_events[0]["runner_wrapper_ok"])
        self.assertTrue(history_events[0]["runner_wrapper_executes_runner_command"])
        self.assertTrue(history_events[0]["runner_wrapper_forwards_arguments"])
        _assert_execution_summary(self, history_events[0], command_dir)
        self.assertEqual(history_summary["latest"]["runner_wrapper_ok"], True)
        self.assertEqual(
            history_summary["latest"]["runner_wrapper_executes_runner_command"],
            True,
        )
        self.assertEqual(history_summary["latest"]["execution_verdict"], "improved")
        self.assertEqual(
            history_summary["latest"]["execution_best_config"],
            "latent@normalize=blocks,scale=0.5",
        )
        self.assertEqual(
            history_summary["latest"]["execution_next_source"],
            "guided_next_follow_up_command",
        )
        self.assertEqual(
            history_summary["latest"]["execution_next_seeds"],
            "109,113,127",
        )
        self.assertEqual(
            history_summary["signals"]["runner_wrapper_ok_counts"],
            {"yes": 1},
        )
        self.assertEqual(
            history_summary["signals"]["execution_verdict_counts"],
            {"improved": 1},
        )
        self.assertEqual(
            history_summary["signals"]["execution_next_source_counts"],
            {"guided_next_follow_up_command": 1},
        )
        self.assertIn("runner_wrapper_ok: yes", run_markdown)
        self.assertIn("runner_wrapper_executes_runner_command: yes", run_markdown)
        self.assertIn("execution_follow_up_verdict: improved", run_markdown)
        self.assertIn(
            "execution_best_config: latent@normalize=blocks,scale=0.5",
            run_markdown,
        )
        self.assertIn(
            "execution_next_command_source: guided_next_follow_up_command",
            run_markdown,
        )
        self.assertIn("execution_next_command_seeds: 109,113,127", run_markdown)
        self.assertIn("execution_next_command_usage: NEW_SEEDS=109,113,127", run_markdown)
        self.assertIn("latest_runner_wrapper_ok: yes", history_markdown)
        self.assertIn(
            "latest_runner_wrapper_executes_runner_command: yes",
            history_markdown,
        )
        self.assertIn("runner_wrapper_ok_counts: yes:1", history_markdown)
        self.assertIn("latest_execution_verdict: improved", history_markdown)
        self.assertIn("execution_verdict_counts: improved:1", history_markdown)
        self.assertIn(
            "latest_execution_next_source: guided_next_follow_up_command",
            history_markdown,
        )
        self.assertIn("latest_execution_next_seeds: 109,113,127", history_markdown)
        self.assertIn(
            "execution_next_source_counts: guided_next_follow_up_command:1",
            history_markdown,
        )

    def test_cli_refreshes_inspection_after_writing_history_reports(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            result = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--dry-run",
                    "--write-inspection-report",
                    "--write-run-report",
                    "--append-run-history",
                    "--write-run-history-report",
                    "--json",
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            payload = json.loads(result.stdout)
            inspection = json.loads(
                (command_dir / "inspection.json").read_text(encoding="utf-8")
            )
            run_report = json.loads(
                (command_dir / "run.json").read_text(encoding="utf-8")
            )
            events = [
                json.loads(line)
                for line in (command_dir / "run_history.jsonl")
                .read_text(encoding="utf-8")
                .splitlines()
            ]
            inspection_outputs = {
                item["label"]: item for item in inspection["declared_outputs"]
            }
            inspection_status = inspection["run_history_summary_status"]
            payload_status = payload["inspection"]["run_history_summary_status"]
            run_report_status = run_report["inspection"]["run_history_summary_status"]

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(len(events), 1)
        self.assertTrue(inspection_outputs["run_json"]["exists"])
        self.assertTrue(inspection_outputs["run_markdown"]["exists"])
        self.assertTrue(inspection_outputs["run_history_jsonl"]["exists"])
        self.assertTrue(inspection_outputs["run_history_markdown"]["exists"])
        self.assertTrue(inspection_outputs["run_history_summary"]["exists"])
        self.assertTrue(inspection_status["exists"])
        self.assertTrue(inspection_status["valid_json"])
        self.assertTrue(inspection_status["schema_ok"])
        self.assertEqual(inspection_status["total_runs"], 1)
        self.assertEqual(inspection_status["history_event_count"], 1)
        self.assertTrue(inspection_status["matches_history_event_count"])
        self.assertIsNone(inspection_status["error"])
        self.assertEqual(payload_status, inspection_status)
        self.assertEqual(run_report_status, inspection_status)
        self.assertEqual(payload["run_history_summary"]["total_runs"], 1)
        self.assertEqual(run_report["run_history_summary"]["total_runs"], 1)

    def test_cli_appends_compact_run_history(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            dry_run = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--dry-run",
                    "--append-run-history",
                    "--write-run-history-report",
                    "--json",
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            executed = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--append-run-history",
                    "--write-run-history-report",
                    "--json",
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            (command_dir / "runner.out").write_text("sentinel\n", encoding="utf-8")
            report_only = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--history-report-only",
                    "--json",
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            dry_payload = json.loads(dry_run.stdout)
            executed_payload = json.loads(executed.stdout)
            report_only_payload = json.loads(report_only.stdout)
            history_path = command_dir / "run_history.jsonl"
            history_markdown_path = command_dir / "run_history.md"
            history_summary_path = command_dir / "run_history_summary.json"
            events = [
                json.loads(line)
                for line in history_path.read_text(encoding="utf-8").splitlines()
            ]
            history_markdown = history_markdown_path.read_text(encoding="utf-8")
            history_summary = json.loads(
                history_summary_path.read_text(encoding="utf-8")
            )
            runner_out = (command_dir / "runner.out").read_text(encoding="utf-8")

        self.assertEqual(dry_run.returncode, 0, dry_run.stderr)
        self.assertEqual(executed.returncode, 0, executed.stderr)
        self.assertEqual(report_only.returncode, 0, report_only.stderr)
        self.assertEqual(runner_out, "sentinel\n")
        self.assertFalse(report_only_payload["executed"])
        self.assertTrue(report_only_payload["history_report_only"])
        self.assertEqual(dry_payload["run_history_jsonl_path"], str(history_path))
        self.assertEqual(executed_payload["run_history_jsonl_path"], str(history_path))
        self.assertEqual(report_only_payload["run_history_jsonl_path"], str(history_path))
        self.assertEqual(
            dry_payload["run_history_markdown_path"],
            str(history_markdown_path),
        )
        self.assertEqual(
            executed_payload["run_history_markdown_path"],
            str(history_markdown_path),
        )
        self.assertEqual(
            report_only_payload["run_history_markdown_path"],
            str(history_markdown_path),
        )
        self.assertEqual(
            dry_payload["run_history_summary_path"],
            str(history_summary_path),
        )
        self.assertEqual(
            executed_payload["run_history_summary_path"],
            str(history_summary_path),
        )
        self.assertEqual(
            report_only_payload["run_history_summary_path"],
            str(history_summary_path),
        )
        dry_summary = dry_payload["run_history_summary"]
        executed_summary = executed_payload["run_history_summary"]
        report_only_summary = report_only_payload["run_history_summary"]
        self.assertEqual(dry_summary["total_runs"], 1)
        self.assertEqual(
            dry_summary["signals"]["status_counts"],
            {"dry-run": 1},
        )
        self.assertEqual(executed_summary["total_runs"], 2)
        self.assertEqual(
            executed_summary["signals"]["status_counts"],
            {"dry-run": 1, "ok": 1},
        )
        self.assertEqual(
            executed_summary["signals"]["current_status_streak"],
            {"status": "ok", "count": 1},
        )
        self.assertEqual(
            executed_summary["signals"]["latest_executed"]["status"],
            "ok",
        )
        self.assertEqual(
            executed_summary["signals"]["latest_executed"]["champion_config"],
            "latent@normalize=blocks,scale=0.5",
        )
        self.assertEqual(
            executed_summary["signals"]["latest_executed"]["execution_verdict"],
            "improved",
        )
        self.assertEqual(
            executed_summary["signals"]["latest_executed"]["execution_best_config"],
            "latent@normalize=blocks,scale=0.5",
        )
        self.assertEqual(
            executed_summary["signals"]["latest_executed"][
                "execution_guidance_action"
            ],
            "confirm_trajectory_with_fresh_seeds",
        )
        self.assertEqual(
            executed_summary["signals"]["latest_executed"]["execution_next_source"],
            "guided_next_follow_up_command",
        )
        self.assertEqual(
            executed_summary["signals"]["latest_executed"]["execution_next_seeds"],
            "109,113,127",
        )
        self.assertEqual(
            executed_summary["signals"]["execution_verdict_counts"],
            {"improved": 1},
        )
        self.assertEqual(
            executed_summary["signals"]["execution_guidance_action_counts"],
            {"confirm_trajectory_with_fresh_seeds": 1},
        )
        self.assertEqual(
            executed_summary["signals"]["execution_next_source_counts"],
            {"guided_next_follow_up_command": 1},
        )
        self.assertEqual(
            executed_summary["signals"]["last_problem"],
            {"status": None, "error": None, "missing_required": None},
        )
        self.assertEqual(report_only_summary["total_runs"], 2)
        self.assertEqual(
            report_only_summary["signals"]["status_counts"],
            {"dry-run": 1, "ok": 1},
        )
        self.assertEqual(history_summary, report_only_summary)
        self.assertEqual(len(events), 2)
        self.assertEqual(
            events[0]["schema"],
            "st.llm_char_vae_context.command_bundle_run_history_event.v1",
        )
        self.assertTrue(events[0]["dry_run"])
        self.assertFalse(events[0]["executed"])
        self.assertFalse(events[1]["dry_run"])
        self.assertTrue(events[1]["executed"])
        self.assertEqual(events[1]["returncode"], 0)
        self.assertEqual(events[1]["target_kind"], "follow_up")
        self.assertEqual(events[1]["target_script_key"], "follow_up_path")
        self.assertEqual(
            events[1]["target_script_path"],
            str(command_dir / "recommended_follow_up.sh"),
        )
        self.assertEqual(
            events[1]["recommendation_context"]["action"],
            "continue_from_accepted",
        )
        self.assertEqual(
            events[1]["recommendation_context"]["champion"]["config"],
            "latent@normalize=blocks,scale=0.5",
        )
        _assert_execution_summary(self, events[1], command_dir)
        self.assertNotIn("stdout", events[1])
        self.assertNotIn("stderr", events[1])
        self.assertNotIn("inspection", events[1])
        self.assertIn("Char VAE Command Bundle Run History", history_markdown)
        self.assertIn("total_runs: 2", history_markdown)
        self.assertIn("success_count: 2", history_markdown)
        self.assertIn("dry_run_count: 1", history_markdown)
        self.assertIn("executed_count: 1", history_markdown)
        self.assertIn("latest_status: ok", history_markdown)
        self.assertIn("latest_target_kind: follow_up", history_markdown)
        self.assertIn("latest_recommendation_action: continue_from_accepted", history_markdown)
        self.assertIn("## Decision Signals", history_markdown)
        self.assertIn("status_counts: dry-run:1, ok:1", history_markdown)
        self.assertIn("target_kind_counts: follow_up:2", history_markdown)
        self.assertIn(
            "recommendation_action_counts: continue_from_accepted:2",
            history_markdown,
        )
        self.assertIn("current_status_streak: ok:1", history_markdown)
        self.assertIn("latest_executed_status: ok", history_markdown)
        self.assertIn("latest_executed_action: continue_from_accepted", history_markdown)
        self.assertIn(
            "latest_executed_champion_config: latent@normalize=blocks,scale=0.5",
            history_markdown,
        )
        self.assertIn(
            "latest_executed_execution_verdict: improved",
            history_markdown,
        )
        self.assertIn(
            "latest_executed_execution_best_config: "
            "latent@normalize=blocks,scale=0.5",
            history_markdown,
        )
        self.assertIn("execution_verdict_counts: improved:1", history_markdown)
        self.assertIn(
            "execution_guidance_action_counts: "
            "confirm_trajectory_with_fresh_seeds:1",
            history_markdown,
        )
        self.assertIn("execution_evidence_status_counts: improved:1", history_markdown)
        self.assertIn(
            "latest_executed_execution_evidence_status: improved",
            history_markdown,
        )
        self.assertIn(
            "latest_executed_execution_next_source: "
            "guided_next_follow_up_command",
            history_markdown,
        )
        self.assertIn(
            "latest_executed_execution_next_seeds: 109,113,127",
            history_markdown,
        )
        self.assertIn(
            "execution_next_source_counts: guided_next_follow_up_command:1",
            history_markdown,
        )
        self.assertIn("last_problem_status: -", history_markdown)
        self.assertIn("## Recent Events", history_markdown)
        self.assertIn("| 2 | ok | next | follow_up | no | yes | 0 |", history_markdown)
        self.assertIn(
            "| improved | improved | no | latent@normalize=blocks,scale=0.5 | 109,113,127 |",
            history_markdown,
        )

    def test_cli_writes_explicit_run_report_outputs(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            command_dir = _write_bundle(root)
            json_out = root / "reports" / "bundle-run.json"
            markdown_out = root / "reports" / "bundle-run.md"
            result = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--json",
                    "--json-out",
                    str(json_out),
                    "--markdown-out",
                    str(markdown_out),
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            payload = json.loads(result.stdout)
            report = json.loads(json_out.read_text(encoding="utf-8"))
            markdown = markdown_out.read_text(encoding="utf-8")

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(payload["run_json_path"], str(json_out))
        self.assertEqual(payload["target_kind"], "follow_up")
        _assert_recommendation_context(self, payload, command_dir)
        self.assertTrue(payload["executed"])
        self.assertEqual(report["returncode"], 0)
        self.assertEqual(report["target_kind"], "follow_up")
        _assert_recommendation_context(self, report, command_dir)
        self.assertEqual(
            report["command_argv"],
            ["bash", str(command_dir / "recommended_next.sh")],
        )
        self.assertGreaterEqual(report["duration_seconds"], 0.0)
        self.assertEqual(report["run_markdown_path"], str(markdown_out))
        self.assertIsNone(report["run_history_jsonl_path"])
        self.assertIsNone(report["run_history_markdown_path"])
        self.assertIsNone(report["run_history_summary_path"])
        self.assertIn("Char VAE Command Bundle Runner", markdown)
        self.assertIn(f"run_json_path: {json_out}", markdown)
        self.assertIn("run_history_jsonl_path: -", markdown)
        self.assertIn("run_history_markdown_path: -", markdown)
        self.assertIn("run_history_summary_path: -", markdown)
        self.assertIn("target_kind: follow_up", markdown)
        self.assertIn("target_script_key: follow_up_path", markdown)
        self.assertIn("Recommendation Context", markdown)
        self.assertIn("recommendation_action: continue_from_accepted", markdown)
        self.assertIn(
            "recommendation_reason: accepted champion remains the safest continuation",
            markdown,
        )
        self.assertIn("champion_config: latent@normalize=blocks,scale=0.5", markdown)
        self.assertIn("fallback_config: raw@normalize=blocks,scale=1.0", markdown)
        self.assertIn("follow_up_command_source: next_follow_up_command", markdown)
        self.assertIn("executed: yes", markdown)
        self.assertIn("duration_seconds:", markdown)


if __name__ == "__main__":
    unittest.main()
