#!/usr/bin/env python3

from __future__ import annotations

import json
import subprocess
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "tools" / "inspect_char_vae_command_bundle.py"
RUNNER_SCRIPT = ROOT / "tools" / "run_char_vae_command_bundle.py"
LOOP_SCRIPT = ROOT / "tools" / "run_char_vae_history_loop.py"


def _write_json(path: Path, payload: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload), encoding="utf-8")


def _write_script(path: Path, *, executable: bool = True) -> None:
    path.write_text("#!/usr/bin/env bash\nset -euo pipefail\n", encoding="utf-8")
    if executable:
        path.chmod(path.stat().st_mode | 0o755)


def _write_runner_script(
    path: Path,
    command_dir: Path,
    *,
    executable: bool = True,
    stale: bool = False,
) -> None:
    runner_command = (
        "env PYTHONNOUSERSITE=1 python3 -P "
        f"{RUNNER_SCRIPT} {command_dir / 'stale'} --write-inspection-report"
        if stale
        else _runner_command(command_dir)
    )
    path.write_text(
        "\n".join(
            [
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                "",
                "# Generated by summarize_char_vae_context_chains.py: run_recommended_next",
                "# target_kind: follow_up",
                "# Runs the recommended next action through bundle inspection first.",
                f'exec {runner_command} "$@"',
                "",
            ]
        ),
        encoding="utf-8",
    )
    if executable:
        path.chmod(path.stat().st_mode | 0o755)


def _runner_command(command_dir: Path) -> str:
    return (
        "env PYTHONNOUSERSITE=1 python3 -P "
        f"{RUNNER_SCRIPT} {command_dir} "
        "--write-inspection-report --write-run-report --append-run-history "
        "--write-run-history-report"
    )


def _history_report_command(command_dir: Path) -> str:
    return (
        "env PYTHONNOUSERSITE=1 python3 -P "
        f"{RUNNER_SCRIPT} {command_dir} --history-report-only"
    )


def _history_next_action_command(command_dir: Path) -> str:
    return (
        "env PYTHONNOUSERSITE=1 python3 -P "
        f"{RUNNER_SCRIPT} {command_dir} --use-history-next-action "
        "--write-inspection-report --write-run-report --append-run-history "
        "--write-run-history-report"
    )


def _history_loop_command(command_dir: Path) -> str:
    return (
        "env PYTHONNOUSERSITE=1 python3 -P "
        f"{LOOP_SCRIPT} {command_dir} --max-steps 3 --fail-on-final-action "
        "review_before_continuing,inspect_history "
        "--fail-on-max-steps-continuation --write-loop-report"
    )


def _history_loop_resume_command(command_dir: Path) -> str:
    return (
        "env PYTHONNOUSERSITE=1 python3 -P "
        f"{LOOP_SCRIPT} {command_dir} --resume-from-report"
    )


def _write_bundle(
    root: Path,
    *,
    missing_comparison_json: bool = False,
    non_executable_follow_up: bool = False,
    include_runner: bool = False,
    non_executable_runner: bool = False,
    stale_runner: bool = False,
) -> Path:
    command_dir = root / "commands"
    command_dir.mkdir(parents=True, exist_ok=True)
    chain = root / "chain" / "chain.json"
    _write_json(chain, {"schema": "st.llm_char_vae_context.chain.v1"})

    comparison_json = command_dir / "comparison.json"
    comparison_markdown = command_dir / "comparison.md"
    run_json = command_dir / "run.json"
    run_markdown = command_dir / "run.md"
    run_history_jsonl = command_dir / "run_history.jsonl"
    run_history_markdown = command_dir / "run_history.md"
    run_history_summary = command_dir / "run_history_summary.json"
    run_loop_json = command_dir / "run_loop.json"
    run_loop_markdown = command_dir / "run_loop.md"
    if not missing_comparison_json:
        _write_json(comparison_json, {"schema": "comparison"})
    comparison_markdown.write_text("# comparison\n", encoding="utf-8")
    (command_dir / "README.md").write_text("# commands\n", encoding="utf-8")

    next_script = command_dir / "recommended_next.sh"
    follow_up_script = command_dir / "recommended_follow_up.sh"
    runner_script = command_dir / "run_recommended_next.sh"
    _write_script(next_script)
    _write_script(follow_up_script, executable=not non_executable_follow_up)
    if include_runner or non_executable_runner or stale_runner:
        _write_runner_script(
            runner_script,
            command_dir,
            executable=not non_executable_runner,
            stale=stale_runner,
        )

    _write_json(
        command_dir / "recommendation.json",
        {
            "schema": "st.llm_char_vae_context.chain_command_manifest.v1",
            "comparison": {
                "schema": "st.llm_char_vae_context.chain_comparison.v1",
                "chain_sources": [str(chain)],
            },
            "recommendation": {
                "action": "continue_from_accepted",
            },
            "command_scripts": {
                "schema": "st.llm_char_vae_context.chain_command_scripts.v1",
                "directory": str(command_dir),
                "next_path": str(next_script),
                "next_kind": "follow_up",
                "follow_up_path": str(follow_up_script),
                "review_path": None,
                "written_count": 2,
                "comparison_json_path": str(comparison_json),
                "comparison_markdown_path": str(comparison_markdown),
                "runner_command": _runner_command(command_dir),
                "runner_path": str(runner_script)
                if include_runner or non_executable_runner or stale_runner
                else None,
                "history_next_action_command": _history_next_action_command(
                    command_dir
                ),
                "history_loop_command": _history_loop_command(command_dir),
                "history_loop_resume_command": _history_loop_resume_command(
                    command_dir
                ),
                "history_report_command": _history_report_command(command_dir),
                "run_json_path": str(run_json),
                "run_markdown_path": str(run_markdown),
                "run_history_jsonl_path": str(run_history_jsonl),
                "run_history_markdown_path": str(run_history_markdown),
                "run_history_summary_path": str(run_history_summary),
                "run_loop_json_path": str(run_loop_json),
                "run_loop_markdown_path": str(run_loop_markdown),
                "readme_path": str(command_dir / "README.md"),
            },
        },
    )
    return command_dir


class InspectCharVaeCommandBundleTests(unittest.TestCase):
    def test_cli_reports_ready_bundle(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            markdown_result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir)],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

        self.assertEqual(result.returncode, 0, result.stderr)
        payload = json.loads(result.stdout)
        self.assertTrue(payload["bundle_ready"])
        self.assertTrue(payload["strict_ready"])
        self.assertEqual(payload["action"], "continue_from_accepted")
        self.assertEqual(payload["next_kind"], "follow_up")
        self.assertEqual(payload["chain_source_count"], 1)
        self.assertEqual(payload["missing_required"], [])
        self.assertEqual(payload["missing_optional"], [])
        self.assertEqual(payload["declared_command_issues"], [])
        self.assertEqual(payload["run_loop_status_issues"], [])
        self.assertEqual(payload["runner_command"], _runner_command(command_dir))
        self.assertEqual(
            payload["history_report_command"],
            _history_report_command(command_dir),
        )
        self.assertEqual(
            payload["history_next_action_command"],
            _history_next_action_command(command_dir),
        )
        self.assertEqual(
            payload["history_loop_command"],
            _history_loop_command(command_dir),
        )
        self.assertEqual(
            payload["history_loop_resume_command"],
            _history_loop_resume_command(command_dir),
        )
        commands = {item["label"]: item for item in payload["declared_commands"]}
        self.assertTrue(commands["runner_command"]["ok"])
        self.assertTrue(commands["history_next_action_command"]["ok"])
        self.assertTrue(commands["history_loop_command"]["ok"])
        self.assertTrue(commands["history_loop_resume_command"]["ok"])
        self.assertTrue(commands["history_report_command"]["ok"])
        self.assertIsNone(commands["history_next_action_command"]["parse_error"])
        self.assertIsNone(commands["history_loop_command"]["parse_error"])
        self.assertIsNone(commands["history_loop_resume_command"]["parse_error"])
        self.assertIsNone(commands["history_report_command"]["parse_error"])
        self.assertTrue(commands["runner_command"]["target_command_dir_ok"])
        self.assertTrue(
            commands["history_next_action_command"]["target_command_dir_ok"]
        )
        self.assertTrue(commands["history_loop_command"]["target_command_dir_ok"])
        self.assertTrue(
            commands["history_loop_resume_command"]["target_command_dir_ok"]
        )
        self.assertTrue(commands["history_report_command"]["target_command_dir_ok"])
        self.assertIn(
            "--use-history-next-action",
            commands["history_next_action_command"]["tokens"],
        )
        self.assertIn(
            "--history-report-only",
            commands["history_report_command"]["tokens"],
        )
        self.assertIn(
            "--write-loop-report",
            commands["history_loop_command"]["tokens"],
        )
        self.assertIn(
            "--resume-from-report",
            commands["history_loop_resume_command"]["tokens"],
        )
        self.assertEqual(
            commands["history_next_action_command"]["required_flags"],
            [
                "run_char_vae_command_bundle.py",
                "--use-history-next-action",
                "--write-inspection-report",
                "--write-run-report",
                "--append-run-history",
                "--write-run-history-report",
            ],
        )
        self.assertEqual(
            commands["history_report_command"]["required_flags"],
            ["run_char_vae_command_bundle.py", "--history-report-only"],
        )
        self.assertEqual(
            commands["history_loop_command"]["required_flags"],
            [
                "run_char_vae_history_loop.py",
                "--max-steps",
                "--fail-on-max-steps-continuation",
                "--write-loop-report",
            ],
        )
        self.assertEqual(
            commands["history_loop_resume_command"]["required_flags"],
            ["run_char_vae_history_loop.py", "--resume-from-report"],
        )
        self.assertEqual(
            commands["history_report_command"]["forbidden_flags"],
            ["--append-run-history"],
        )
        self.assertEqual(payload["run_json_path"], str(command_dir / "run.json"))
        self.assertEqual(
            payload["run_history_summary_path"],
            str(command_dir / "run_history_summary.json"),
        )
        self.assertEqual(
            payload["run_history_summary_status"],
            {
                "path": str(command_dir / "run_history_summary.json"),
                "exists": False,
                "valid_json": None,
                "schema": None,
                "schema_ok": None,
                "total_runs": None,
                "next_action": None,
                "next_action_reason": None,
                "next_action_target": None,
                "next_action_command_source": None,
                "next_action_script_path": None,
                "next_action_default_new_seeds": None,
                "next_action_should_continue": None,
                "next_action_schema_ok": None,
                "history_event_count": None,
                "matches_history_event_count": None,
                "error": None,
            },
        )
        self.assertEqual(
            payload["run_loop_status"],
            {
                "path": str(command_dir / "run_loop.json"),
                "exists": False,
                "valid_json": None,
                "schema": None,
                "schema_ok": None,
                "command_dir": None,
                "command_dir_matches": None,
                "handoff_status": None,
                "handoff_reason": None,
                "handoff_severity": None,
                "handoff_requires_attention": None,
                "handoff_recommended_action": None,
                "max_steps": None,
                "step_count": None,
                "executed_count": None,
                "success_count": None,
                "failure_count": None,
                "stop_reason": None,
                "fail_on_final_actions": None,
                "final_action_failed": None,
                "fail_on_max_steps_continuation": None,
                "max_steps_continuation_failed": None,
                "returncode": None,
                "error": None,
                "final_next_action": None,
                "final_next_action_reason": None,
                "final_next_action_target": None,
                "final_next_action_command_source": None,
                "final_next_action_script_path": None,
                "final_next_action_default_new_seeds": None,
                "final_next_action_should_continue": None,
                "final_next_action_runnable": None,
                "continuation_command": None,
                "resume_from_report_command": None,
                "resume_from_report_command_present": None,
                "resume_from_report_command_ok": None,
                "resume_from_report_command_target_dir_ok": None,
                "resume_from_report_command_report_path_ok": None,
                "resume_from_report_command_parse_error": None,
                "resume_from_report_command_missing_required_flags": None,
                "continuation_command_expected": None,
                "continuation_command_present": None,
                "continuation_command_ok": None,
                "continuation_command_target_dir_ok": None,
                "continuation_command_parse_error": None,
                "continuation_command_missing_required_flags": None,
            },
        )
        self.assertEqual(
            payload["declared_outputs"],
            [
                {
                    "label": "run_json",
                    "path": str(command_dir / "run.json"),
                    "exists": False,
                },
                {
                    "label": "run_markdown",
                    "path": str(command_dir / "run.md"),
                    "exists": False,
                },
                {
                    "label": "run_history_jsonl",
                    "path": str(command_dir / "run_history.jsonl"),
                    "exists": False,
                },
                {
                    "label": "run_history_markdown",
                    "path": str(command_dir / "run_history.md"),
                    "exists": False,
                },
                {
                    "label": "run_history_summary",
                    "path": str(command_dir / "run_history_summary.json"),
                    "exists": False,
                },
                {
                    "label": "run_loop_json",
                    "path": str(command_dir / "run_loop.json"),
                    "exists": False,
                },
                {
                    "label": "run_loop_markdown",
                    "path": str(command_dir / "run_loop.md"),
                    "exists": False,
                },
            ],
        )
        self.assertEqual(markdown_result.returncode, 0, markdown_result.stderr)
        self.assertIn("Char VAE Command Bundle Inspection", markdown_result.stdout)
        self.assertIn("bundle_ready: yes", markdown_result.stdout)
        self.assertIn("Declared Run Outputs", markdown_result.stdout)
        self.assertIn("Declared Commands", markdown_result.stdout)
        self.assertIn("declared_command_issues: -", markdown_result.stdout)
        self.assertIn("history_report_command", markdown_result.stdout)
        self.assertIn("history_loop_command", markdown_result.stdout)
        self.assertIn("history_loop_resume_command", markdown_result.stdout)
        self.assertIn("--history-report-only", markdown_result.stdout)
        self.assertIn("--write-loop-report", markdown_result.stdout)
        self.assertIn("--resume-from-report", markdown_result.stdout)
        self.assertIn("run_history_summary", markdown_result.stdout)
        self.assertIn("run_loop_status_issues: -", markdown_result.stdout)
        self.assertIn("run_loop_handoff_recommended_action: -", markdown_result.stdout)
        self.assertIn("run_history_summary_valid_json: -", markdown_result.stdout)
        self.assertIn("run_loop_valid_json: -", markdown_result.stdout)

    def test_cli_reports_declared_runner_wrapper(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp), include_runner=True)
            result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            markdown_result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir)],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

        self.assertEqual(result.returncode, 0, result.stderr)
        payload = json.loads(result.stdout)
        runner_path = str(command_dir / "run_recommended_next.sh")
        checks = {item["label"]: item for item in payload["checks"]}
        self.assertTrue(payload["strict_ready"])
        self.assertEqual(payload["runner_path"], runner_path)
        self.assertTrue(payload["runner_wrapper_status"]["ok"])
        self.assertTrue(payload["runner_wrapper_status"]["contains_runner_command"])
        self.assertTrue(payload["runner_wrapper_status"]["executes_runner_command"])
        self.assertTrue(payload["runner_wrapper_status"]["forwards_arguments"])
        self.assertTrue(checks["runner_script"]["ok"])
        self.assertEqual(checks["runner_script"]["path"], runner_path)
        self.assertEqual(markdown_result.returncode, 0, markdown_result.stderr)
        self.assertIn(f"runner_path: {runner_path}", markdown_result.stdout)
        self.assertIn("runner_wrapper_ok: yes", markdown_result.stdout)

    def test_cli_flags_unsafe_history_report_command(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            manifest_path = command_dir / "recommendation.json"
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            manifest["command_scripts"][
                "history_report_command"
            ] = f"{_history_report_command(command_dir)} --append-run-history"
            manifest_path.write_text(
                json.dumps(manifest, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            markdown_result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir)],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

        self.assertEqual(result.returncode, 0, result.stderr)
        payload = json.loads(result.stdout)
        self.assertTrue(payload["bundle_ready"])
        self.assertFalse(payload["strict_ready"])
        self.assertEqual(payload["declared_command_issues"], ["history_report_command"])
        self.assertEqual(payload["missing_optional"], ["history_report_command"])
        commands = {item["label"]: item for item in payload["declared_commands"]}
        self.assertFalse(commands["history_report_command"]["ok"])
        self.assertEqual(
            commands["history_report_command"]["forbidden_flags_present"],
            ["--append-run-history"],
        )
        self.assertEqual(markdown_result.returncode, 0, markdown_result.stderr)
        self.assertIn("strict_ready: no", markdown_result.stdout)
        self.assertIn(
            "declared_command_issues: history_report_command",
            markdown_result.stdout,
        )
        self.assertIn("--append-run-history", markdown_result.stdout)

    def test_cli_flags_declared_command_targeting_another_bundle(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            command_dir = _write_bundle(root)
            other_command_dir = root / "other-commands"
            manifest_path = command_dir / "recommendation.json"
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            manifest["command_scripts"][
                "history_report_command"
            ] = _history_report_command(other_command_dir)
            manifest_path.write_text(
                json.dumps(manifest, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            markdown_result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir)],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

        self.assertEqual(result.returncode, 0, result.stderr)
        payload = json.loads(result.stdout)
        self.assertFalse(payload["strict_ready"])
        self.assertEqual(payload["declared_command_issues"], ["history_report_command"])
        commands = {item["label"]: item for item in payload["declared_commands"]}
        self.assertFalse(commands["history_report_command"]["ok"])
        self.assertFalse(commands["history_report_command"]["target_command_dir_ok"])
        self.assertEqual(markdown_result.returncode, 0, markdown_result.stderr)
        self.assertIn("target_dir_ok", markdown_result.stdout)
        self.assertIn("strict_ready: no", markdown_result.stdout)

    def test_cli_ignores_forbidden_flag_substrings_inside_command_paths(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            manifest_path = command_dir / "recommendation.json"
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            fake_script = (
                Path(tmp)
                / "safe-directory-name-with---append-run-history"
                / "run_char_vae_command_bundle.py"
            )
            manifest["command_scripts"]["history_report_command"] = (
                "env PYTHONNOUSERSITE=1 python3 -P "
                f"{fake_script} {command_dir} --history-report-only"
            )
            manifest_path.write_text(
                json.dumps(manifest, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

        self.assertEqual(result.returncode, 0, result.stderr)
        payload = json.loads(result.stdout)
        self.assertTrue(payload["strict_ready"])
        self.assertEqual(payload["declared_command_issues"], [])
        commands = {item["label"]: item for item in payload["declared_commands"]}
        self.assertTrue(commands["history_report_command"]["ok"])
        self.assertEqual(
            commands["history_report_command"]["forbidden_flags_present"],
            [],
        )

    def test_cli_flags_unparseable_declared_command(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            manifest_path = command_dir / "recommendation.json"
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            manifest["command_scripts"][
                "history_report_command"
            ] = "'unterminated --history-report-only"
            manifest_path.write_text(
                json.dumps(manifest, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            markdown_result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir)],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

        self.assertEqual(result.returncode, 0, result.stderr)
        payload = json.loads(result.stdout)
        self.assertFalse(payload["strict_ready"])
        commands = {item["label"]: item for item in payload["declared_commands"]}
        self.assertFalse(commands["history_report_command"]["ok"])
        self.assertIsNotNone(commands["history_report_command"]["parse_error"])
        self.assertEqual(
            commands["history_report_command"]["missing_required_flags"],
            ["run_char_vae_command_bundle.py", "--history-report-only"],
        )
        self.assertEqual(markdown_result.returncode, 0, markdown_result.stderr)
        self.assertIn("parse_error", markdown_result.stdout)

    def test_cli_writes_default_inspection_reports(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            result = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--write-report",
                    "--json",
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            json_report = command_dir / "inspection.json"
            markdown_report = command_dir / "inspection.md"
            json_report_path = str(json_report.resolve())
            markdown_report_path = str(markdown_report.resolve())
            json_report_exists = json_report.exists()
            markdown_report_exists = markdown_report.exists()
            stdout_payload = json.loads(result.stdout)
            report_payload = json.loads(json_report.read_text(encoding="utf-8"))
            markdown = markdown_report.read_text(encoding="utf-8")

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertTrue(json_report_exists)
        self.assertTrue(markdown_report_exists)
        self.assertEqual(stdout_payload["inspection_json_path"], json_report_path)
        self.assertEqual(
            stdout_payload["inspection_markdown_path"],
            markdown_report_path,
        )
        self.assertTrue(report_payload["bundle_ready"])
        self.assertTrue(report_payload["strict_ready"])
        self.assertEqual(report_payload["inspection_json_path"], json_report_path)
        self.assertEqual(
            report_payload["inspection_markdown_path"],
            markdown_report_path,
        )
        self.assertIn("Char VAE Command Bundle Inspection", markdown)
        self.assertIn(f"inspection_json_path: {json_report_path}", markdown)
        self.assertIn(f"inspection_markdown_path: {markdown_report_path}", markdown)
        self.assertIn("run_history_summary_path:", markdown)
        self.assertIn("Declared Run Outputs", markdown)

    def test_cli_validates_existing_run_history_summary(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            history_path = command_dir / "run_history.jsonl"
            summary_path = command_dir / "run_history_summary.json"
            history_events = [
                {
                    "schema": "st.llm_char_vae_context.command_bundle_run_history_event.v1",
                    "returncode": 0,
                },
                {
                    "schema": "st.llm_char_vae_context.command_bundle_run_history_event.v1",
                    "returncode": 0,
                },
            ]
            history_jsonl = "".join(
                json.dumps(event, sort_keys=True) + "\n"
                for event in history_events
            )
            history_path.write_text(
                history_jsonl,
                encoding="utf-8",
            )
            _write_json(
                summary_path,
                {
                    "schema": "st.llm_char_vae_context.command_bundle_run_history_summary.v1",
                    "total_runs": 2,
                    "next_action": {
                        "schema": (
                            "st.llm_char_vae_context."
                            "command_bundle_history_next_action.v1"
                        ),
                        "action": "run_execution_next",
                        "reason": (
                            "latest execution summary exposes a next command"
                        ),
                        "target": "execution-next",
                        "command_source": "guided_next_follow_up_command",
                        "script_path": str(command_dir / "guided_next.sh"),
                        "default_new_seeds": [109, 113, 127],
                        "should_continue": True,
                    },
                    "signals": {"status_counts": {"ok": 2}},
                },
            )
            result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            markdown_result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir)],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

        self.assertEqual(result.returncode, 0, result.stderr)
        payload = json.loads(result.stdout)
        status = payload["run_history_summary_status"]
        self.assertTrue(status["exists"])
        self.assertTrue(status["valid_json"])
        self.assertTrue(status["schema_ok"])
        self.assertEqual(status["total_runs"], 2)
        self.assertEqual(status["next_action"], "run_execution_next")
        self.assertEqual(
            status["next_action_reason"],
            "latest execution summary exposes a next command",
        )
        self.assertEqual(status["next_action_target"], "execution-next")
        self.assertEqual(
            status["next_action_command_source"],
            "guided_next_follow_up_command",
        )
        self.assertEqual(
            status["next_action_script_path"],
            str(command_dir / "guided_next.sh"),
        )
        self.assertEqual(status["next_action_default_new_seeds"], [109, 113, 127])
        self.assertIs(status["next_action_should_continue"], True)
        self.assertIs(status["next_action_schema_ok"], True)
        self.assertEqual(status["history_event_count"], 2)
        self.assertTrue(status["matches_history_event_count"])
        self.assertIsNone(status["error"])
        self.assertEqual(markdown_result.returncode, 0, markdown_result.stderr)
        self.assertIn("run_history_summary_valid_json: yes", markdown_result.stdout)
        self.assertIn("run_history_next_action: run_execution_next", markdown_result.stdout)
        self.assertIn(
            "run_history_next_action_reason: "
            "latest execution summary exposes a next command",
            markdown_result.stdout,
        )
        self.assertIn("run_history_next_action_target: execution-next", markdown_result.stdout)
        self.assertIn(
            "run_history_next_action_command_source: guided_next_follow_up_command",
            markdown_result.stdout,
        )
        self.assertIn(
            f"run_history_next_action_script_path: {command_dir / 'guided_next.sh'}",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_history_next_action_default_new_seeds: 109,113,127",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_history_next_action_should_continue: yes",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_history_next_action_schema_ok: yes",
            markdown_result.stdout,
        )
        self.assertIn("run_history_summary_matches_jsonl: yes", markdown_result.stdout)

    def test_cli_validates_existing_run_loop_summary(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            run_loop_path = command_dir / "run_loop.json"
            _write_json(
                run_loop_path,
                {
                    "schema": "st.llm_char_vae_context.command_bundle_history_loop.v1",
                    "command_dir": str(command_dir),
                    "max_steps": 3,
                    "step_count": 2,
                    "executed_count": 2,
                    "success_count": 2,
                    "failure_count": 0,
                    "stop_reason": "history_next_action_stopped",
                    "fail_on_final_actions": [
                        "review_before_continuing",
                        "inspect_history",
                    ],
                    "final_action_failed": False,
                    "fail_on_max_steps_continuation": True,
                    "max_steps_continuation_failed": False,
                    "returncode": 0,
                    "error": None,
                    "final_next_action": {
                        "schema": (
                            "st.llm_char_vae_context."
                            "command_bundle_history_next_action.v1"
                        ),
                        "action": "collect_next_command",
                        "reason": (
                            "latest execution can continue but has no next script"
                        ),
                        "target": None,
                        "command_source": "guided_next_follow_up_command",
                        "script_path": None,
                        "default_new_seeds": "109,113,127",
                        "should_continue": False,
                    },
                    "final_next_action_runnable": False,
                    "continuation_command": None,
                    "resume_from_report_command": None,
                    "steps": [
                        {
                            "index": 1,
                            "target": "next",
                            "executed": True,
                            "returncode": 0,
                        },
                        {
                            "index": 2,
                            "target": "execution-next",
                            "executed": True,
                            "returncode": 0,
                        },
                    ],
                },
            )
            result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            markdown_result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir)],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

        self.assertEqual(result.returncode, 0, result.stderr)
        payload = json.loads(result.stdout)
        self.assertTrue(payload["strict_ready"])
        self.assertEqual(payload["missing_optional"], [])
        self.assertEqual(payload["run_loop_status_issues"], [])
        status = payload["run_loop_status"]
        self.assertTrue(status["exists"])
        self.assertTrue(status["valid_json"])
        self.assertTrue(status["schema_ok"])
        self.assertEqual(status["command_dir"], str(command_dir))
        self.assertTrue(status["command_dir_matches"])
        self.assertEqual(status["handoff_status"], "awaiting_next_command")
        self.assertEqual(
            status["handoff_reason"],
            "latest execution can continue but has no next script",
        )
        self.assertEqual(status["handoff_severity"], "attention")
        self.assertIs(status["handoff_requires_attention"], True)
        self.assertEqual(status["handoff_recommended_action"], "collect_next_command")
        self.assertEqual(status["max_steps"], 3)
        self.assertEqual(status["step_count"], 2)
        self.assertEqual(status["executed_count"], 2)
        self.assertEqual(status["success_count"], 2)
        self.assertEqual(status["failure_count"], 0)
        self.assertEqual(status["stop_reason"], "history_next_action_stopped")
        self.assertEqual(
            status["fail_on_final_actions"],
            ["review_before_continuing", "inspect_history"],
        )
        self.assertIs(status["final_action_failed"], False)
        self.assertIs(status["fail_on_max_steps_continuation"], True)
        self.assertIs(status["max_steps_continuation_failed"], False)
        self.assertEqual(status["returncode"], 0)
        self.assertEqual(status["final_next_action"], "collect_next_command")
        self.assertEqual(
            status["final_next_action_reason"],
            "latest execution can continue but has no next script",
        )
        self.assertIsNone(status["final_next_action_target"])
        self.assertEqual(
            status["final_next_action_command_source"],
            "guided_next_follow_up_command",
        )
        self.assertIsNone(status["final_next_action_script_path"])
        self.assertEqual(status["final_next_action_default_new_seeds"], "109,113,127")
        self.assertIs(status["final_next_action_should_continue"], False)
        self.assertIs(status["final_next_action_runnable"], False)
        self.assertIsNone(status["continuation_command"])
        self.assertIsNone(status["resume_from_report_command"])
        self.assertIs(status["resume_from_report_command_present"], False)
        self.assertIsNone(status["resume_from_report_command_ok"])
        self.assertIsNone(status["resume_from_report_command_target_dir_ok"])
        self.assertIsNone(status["resume_from_report_command_report_path_ok"])
        self.assertIsNone(status["resume_from_report_command_parse_error"])
        self.assertEqual(
            status["resume_from_report_command_missing_required_flags"],
            [],
        )
        self.assertIs(status["continuation_command_expected"], False)
        self.assertIs(status["continuation_command_present"], False)
        self.assertIsNone(status["continuation_command_ok"])
        self.assertIsNone(status["continuation_command_target_dir_ok"])
        self.assertIsNone(status["continuation_command_parse_error"])
        self.assertEqual(status["continuation_command_missing_required_flags"], [])
        self.assertIsNone(status["error"])
        self.assertEqual(markdown_result.returncode, 0, markdown_result.stderr)
        self.assertIn("run_loop_valid_json: yes", markdown_result.stdout)
        self.assertIn("run_loop_schema_ok: yes", markdown_result.stdout)
        self.assertIn("run_loop_command_dir_matches: yes", markdown_result.stdout)
        self.assertIn(
            "run_loop_handoff_status: awaiting_next_command",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_handoff_reason: "
            "latest execution can continue but has no next script",
            markdown_result.stdout,
        )
        self.assertIn("run_loop_handoff_severity: attention", markdown_result.stdout)
        self.assertIn(
            "run_loop_handoff_requires_attention: yes",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_handoff_recommended_action: collect_next_command",
            markdown_result.stdout,
        )
        self.assertIn("run_loop_step_count: 2", markdown_result.stdout)
        self.assertIn(
            "run_loop_stop_reason: history_next_action_stopped",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_fail_on_final_actions: "
            "review_before_continuing,inspect_history",
            markdown_result.stdout,
        )
        self.assertIn("run_loop_final_action_failed: no", markdown_result.stdout)
        self.assertIn(
            "run_loop_fail_on_max_steps_continuation: yes",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_max_steps_continuation_failed: no",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_final_next_action: collect_next_command",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_final_next_action_should_continue: no",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_final_next_action_command_source: "
            "guided_next_follow_up_command",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_final_next_action_default_new_seeds: 109,113,127",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_final_next_action_runnable: no",
            markdown_result.stdout,
        )
        self.assertIn("run_loop_continuation_command: -", markdown_result.stdout)
        self.assertIn(
            "run_loop_resume_from_report_command: -",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_continuation_command_expected: no",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_continuation_command_present: no",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_continuation_command_ok: -",
            markdown_result.stdout,
        )

    def test_cli_derives_legacy_run_loop_continuation_handoff(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            next_script = command_dir / "executed_follow_up" / "guided_next.sh"
            continuation_command = (
                "env PYTHONNOUSERSITE=1 python3 -P "
                f"{ROOT / 'tools' / 'run_char_vae_history_loop.py'} "
                f"{command_dir} --max-steps 1 --fail-on-max-steps-continuation "
                "--write-loop-report"
            )
            resume_from_report_command = (
                "env PYTHONNOUSERSITE=1 python3 -P "
                f"{ROOT / 'tools' / 'run_char_vae_history_loop.py'} "
                f"{command_dir} --resume-from-report"
            )
            _write_json(
                command_dir / "run_loop.json",
                {
                    "schema": "st.llm_char_vae_context.command_bundle_history_loop.v1",
                    "command_dir": str(command_dir),
                    "max_steps": 1,
                    "step_count": 1,
                    "executed_count": 1,
                    "success_count": 1,
                    "failure_count": 0,
                    "stop_reason": "max_steps_reached",
                    "fail_on_final_actions": [
                        "review_before_continuing",
                        "inspect_history",
                    ],
                    "final_action_failed": False,
                    "fail_on_max_steps_continuation": True,
                    "max_steps_continuation_failed": True,
                    "returncode": 1,
                    "error": (
                        "max steps reached with runnable final next action: "
                        "run_execution_next"
                    ),
                    "final_next_action": {
                        "schema": (
                            "st.llm_char_vae_context."
                            "command_bundle_history_next_action.v1"
                        ),
                        "action": "run_execution_next",
                        "reason": "latest execution summary exposes a next command",
                        "target": "execution-next",
                        "command_source": "guided_next_follow_up_command",
                        "script_path": str(next_script),
                        "default_new_seeds": "109,113,127",
                        "should_continue": True,
                    },
                    "continuation_command": continuation_command,
                    "resume_from_report_command": resume_from_report_command,
                    "steps": [],
                },
            )
            result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            markdown_result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir)],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

        self.assertEqual(result.returncode, 0, result.stderr)
        payload = json.loads(result.stdout)
        status = payload["run_loop_status"]
        self.assertEqual(status["handoff_status"], "continuation_ready")
        self.assertEqual(
            status["handoff_reason"],
            "latest execution summary exposes a next command",
        )
        self.assertIs(status["final_next_action_runnable"], True)
        self.assertEqual(status["continuation_command"], continuation_command)
        self.assertEqual(
            status["resume_from_report_command"],
            resume_from_report_command,
        )
        self.assertIs(status["resume_from_report_command_present"], True)
        self.assertIs(status["resume_from_report_command_ok"], True)
        self.assertIs(status["resume_from_report_command_target_dir_ok"], True)
        self.assertIs(status["resume_from_report_command_report_path_ok"], True)
        self.assertIsNone(status["resume_from_report_command_parse_error"])
        self.assertEqual(
            status["resume_from_report_command_missing_required_flags"],
            [],
        )
        self.assertTrue(status["command_dir_matches"])
        self.assertEqual(status["handoff_severity"], "ready")
        self.assertIs(status["handoff_requires_attention"], False)
        self.assertEqual(
            status["handoff_recommended_action"],
            "run_resume_from_report_command",
        )
        self.assertIs(status["continuation_command_expected"], True)
        self.assertIs(status["continuation_command_present"], True)
        self.assertIs(status["continuation_command_ok"], True)
        self.assertIs(status["continuation_command_target_dir_ok"], True)
        self.assertIsNone(status["continuation_command_parse_error"])
        self.assertEqual(status["continuation_command_missing_required_flags"], [])
        self.assertEqual(status["returncode"], 1)
        self.assertIn(
            "run_loop_handoff_status: continuation_ready",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_final_next_action_runnable: yes",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_continuation_command_ok: yes",
            markdown_result.stdout,
        )
        self.assertIn(
            f"run_loop_resume_from_report_command: {resume_from_report_command}",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_resume_from_report_command_ok: yes",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_resume_from_report_command_report_path_ok: yes",
            markdown_result.stdout,
        )

    def test_cli_keeps_continuation_guidance_without_resume_command(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            continuation_command = (
                "env PYTHONNOUSERSITE=1 python3 -P "
                f"{ROOT / 'tools' / 'run_char_vae_history_loop.py'} "
                f"{command_dir} --max-steps 1 --write-loop-report"
            )
            _write_json(
                command_dir / "run_loop.json",
                {
                    "schema": "st.llm_char_vae_context.command_bundle_history_loop.v1",
                    "command_dir": str(command_dir),
                    "handoff_status": "continuation_ready",
                    "handoff_reason": "legacy continuation is runnable",
                    "max_steps": 1,
                    "step_count": 1,
                    "executed_count": 1,
                    "success_count": 1,
                    "failure_count": 0,
                    "stop_reason": "max_steps_reached",
                    "returncode": 0,
                    "final_next_action": {
                        "action": "run_execution_next",
                        "reason": "latest execution summary exposes a next command",
                        "target": "execution-next",
                        "command_source": "guided_next_follow_up_command",
                        "script_path": str(command_dir / "guided_next.sh"),
                        "should_continue": True,
                    },
                    "final_next_action_runnable": True,
                    "continuation_command": continuation_command,
                    "steps": [],
                },
            )
            result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

        self.assertEqual(result.returncode, 0, result.stderr)
        payload = json.loads(result.stdout)
        self.assertTrue(payload["strict_ready"])
        status = payload["run_loop_status"]
        self.assertEqual(status["handoff_status"], "continuation_ready")
        self.assertEqual(
            status["handoff_recommended_action"],
            "run_continuation_command",
        )
        self.assertIsNone(status["resume_from_report_command"])
        self.assertIs(status["resume_from_report_command_present"], False)
        self.assertIsNone(status["resume_from_report_command_ok"])

    def test_cli_surfaces_failed_run_loop_handoff_guidance(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp))
            _write_json(
                command_dir / "run_loop.json",
                {
                    "schema": "st.llm_char_vae_context.command_bundle_history_loop.v1",
                    "command_dir": str(command_dir),
                    "handoff_status": "failed",
                    "handoff_reason": "--max-steps must be at least 1",
                    "max_steps": 0,
                    "step_count": 0,
                    "executed_count": 0,
                    "success_count": 0,
                    "failure_count": 0,
                    "stop_reason": "loop_setup_failed",
                    "fail_on_final_actions": [
                        "review_before_continuing",
                        "inspect_history",
                    ],
                    "final_action_failed": False,
                    "fail_on_max_steps_continuation": False,
                    "max_steps_continuation_failed": False,
                    "returncode": 1,
                    "error": "--max-steps must be at least 1",
                    "final_next_action": None,
                    "final_next_action_runnable": False,
                    "continuation_command": None,
                    "steps": [],
                },
            )
            result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            markdown_result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir)],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

        self.assertEqual(result.returncode, 0, result.stderr)
        payload = json.loads(result.stdout)
        self.assertTrue(payload["strict_ready"])
        self.assertEqual(payload["run_loop_status_issues"], [])
        status = payload["run_loop_status"]
        self.assertEqual(status["handoff_status"], "failed")
        self.assertEqual(status["handoff_severity"], "failed")
        self.assertIs(status["handoff_requires_attention"], True)
        self.assertEqual(status["handoff_recommended_action"], "inspect_failure")
        self.assertEqual(status["returncode"], 1)
        self.assertEqual(status["stop_reason"], "loop_setup_failed")
        self.assertEqual(markdown_result.returncode, 0, markdown_result.stderr)
        self.assertIn("run_loop_handoff_status: failed", markdown_result.stdout)
        self.assertIn("run_loop_handoff_severity: failed", markdown_result.stdout)
        self.assertIn(
            "run_loop_handoff_recommended_action: inspect_failure",
            markdown_result.stdout,
        )

    def test_cli_flags_stale_run_loop_resume_report_target(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            command_dir = _write_bundle(root)
            stale_report = root / "stale_run_loop.json"
            continuation_command = (
                "env PYTHONNOUSERSITE=1 python3 -P "
                f"{ROOT / 'tools' / 'run_char_vae_history_loop.py'} "
                f"{command_dir} --max-steps 1 --write-loop-report"
            )
            resume_from_report_command = (
                "env PYTHONNOUSERSITE=1 python3 -P "
                f"{ROOT / 'tools' / 'run_char_vae_history_loop.py'} "
                f"{command_dir} --resume-from-report {stale_report}"
            )
            _write_json(
                command_dir / "run_loop.json",
                {
                    "schema": "st.llm_char_vae_context.command_bundle_history_loop.v1",
                    "command_dir": str(command_dir),
                    "handoff_status": "continuation_ready",
                    "handoff_reason": "latest execution summary exposes a next command",
                    "max_steps": 1,
                    "step_count": 1,
                    "executed_count": 1,
                    "success_count": 1,
                    "failure_count": 0,
                    "stop_reason": "max_steps_reached",
                    "returncode": 0,
                    "final_next_action": {
                        "action": "run_execution_next",
                        "reason": "latest execution summary exposes a next command",
                        "target": "execution-next",
                        "command_source": "guided_next_follow_up_command",
                        "script_path": str(command_dir / "guided_next.sh"),
                        "should_continue": True,
                    },
                    "final_next_action_runnable": True,
                    "continuation_command": continuation_command,
                    "resume_from_report_command": resume_from_report_command,
                    "steps": [],
                },
            )
            result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            strict_result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json", "--strict"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            markdown_result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir)],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(strict_result.returncode, 1)
        payload = json.loads(result.stdout)
        strict_payload = json.loads(strict_result.stdout)
        self.assertFalse(payload["strict_ready"])
        self.assertFalse(strict_payload["strict_ready"])
        self.assertEqual(
            payload["run_loop_status_issues"],
            ["run_loop_resume_from_report_command"],
        )
        self.assertEqual(
            payload["missing_optional"],
            ["run_loop_resume_from_report_command"],
        )
        status = payload["run_loop_status"]
        self.assertEqual(status["handoff_severity"], "invalid")
        self.assertIs(status["handoff_requires_attention"], True)
        self.assertEqual(
            status["handoff_recommended_action"],
            "repair_run_loop_report",
        )
        self.assertIs(status["continuation_command_ok"], True)
        self.assertIs(status["resume_from_report_command_present"], True)
        self.assertIs(status["resume_from_report_command_ok"], False)
        self.assertIs(status["resume_from_report_command_target_dir_ok"], True)
        self.assertIs(status["resume_from_report_command_report_path_ok"], False)
        self.assertIsNone(status["resume_from_report_command_parse_error"])
        self.assertEqual(
            status["resume_from_report_command_missing_required_flags"],
            [],
        )
        self.assertEqual(markdown_result.returncode, 0, markdown_result.stderr)
        self.assertIn(
            "run_loop_status_issues: run_loop_resume_from_report_command",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_resume_from_report_command_ok: no",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_resume_from_report_command_report_path_ok: no",
            markdown_result.stdout,
        )

    def test_cli_flags_stale_run_loop_handoff_target(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            command_dir = _write_bundle(root)
            other_command_dir = root / "other-commands"
            continuation_command = (
                "env PYTHONNOUSERSITE=1 python3 -P "
                f"{ROOT / 'tools' / 'run_char_vae_history_loop.py'} "
                f"{other_command_dir} --max-steps 1 --write-loop-report"
            )
            _write_json(
                command_dir / "run_loop.json",
                {
                    "schema": "st.llm_char_vae_context.command_bundle_history_loop.v1",
                    "command_dir": str(other_command_dir),
                    "handoff_status": "continuation_ready",
                    "handoff_reason": "latest execution summary exposes a next command",
                    "max_steps": 1,
                    "step_count": 1,
                    "executed_count": 1,
                    "success_count": 1,
                    "failure_count": 0,
                    "stop_reason": "max_steps_reached",
                    "fail_on_final_actions": [
                        "review_before_continuing",
                        "inspect_history",
                    ],
                    "final_action_failed": False,
                    "fail_on_max_steps_continuation": False,
                    "max_steps_continuation_failed": False,
                    "returncode": 0,
                    "error": None,
                    "final_next_action": {
                        "schema": (
                            "st.llm_char_vae_context."
                            "command_bundle_history_next_action.v1"
                        ),
                        "action": "run_execution_next",
                        "reason": "latest execution summary exposes a next command",
                        "target": "execution-next",
                        "command_source": "guided_next_follow_up_command",
                        "script_path": str(other_command_dir / "guided_next.sh"),
                        "default_new_seeds": "109,113,127",
                        "should_continue": True,
                    },
                    "final_next_action_runnable": True,
                    "continuation_command": continuation_command,
                    "steps": [],
                },
            )
            result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            strict_result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json", "--strict"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            markdown_result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir)],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(strict_result.returncode, 1)
        payload = json.loads(result.stdout)
        strict_payload = json.loads(strict_result.stdout)
        self.assertFalse(payload["strict_ready"])
        self.assertEqual(
            payload["run_loop_status_issues"],
            ["run_loop_command_dir", "run_loop_continuation_command"],
        )
        self.assertEqual(
            payload["missing_optional"],
            ["run_loop_command_dir", "run_loop_continuation_command"],
        )
        self.assertFalse(strict_payload["strict_ready"])
        status = payload["run_loop_status"]
        self.assertFalse(status["command_dir_matches"])
        self.assertEqual(status["handoff_severity"], "invalid")
        self.assertIs(status["handoff_requires_attention"], True)
        self.assertEqual(
            status["handoff_recommended_action"],
            "repair_run_loop_report",
        )
        self.assertIs(status["continuation_command_expected"], True)
        self.assertIs(status["continuation_command_present"], True)
        self.assertIs(status["continuation_command_ok"], False)
        self.assertIs(status["continuation_command_target_dir_ok"], False)
        self.assertEqual(status["continuation_command_missing_required_flags"], [])
        self.assertEqual(markdown_result.returncode, 0, markdown_result.stderr)
        self.assertIn("strict_ready: no", markdown_result.stdout)
        self.assertIn(
            "missing_optional: run_loop_command_dir, "
            "run_loop_continuation_command",
            markdown_result.stdout,
        )
        self.assertIn(
            "run_loop_status_issues: run_loop_command_dir, "
            "run_loop_continuation_command",
            markdown_result.stdout,
        )
        self.assertIn("run_loop_handoff_severity: invalid", markdown_result.stdout)
        self.assertIn(
            "run_loop_handoff_recommended_action: repair_run_loop_report",
            markdown_result.stdout,
        )
        self.assertIn("run_loop_command_dir_matches: no", markdown_result.stdout)
        self.assertIn(
            "run_loop_continuation_command_target_dir_ok: no",
            markdown_result.stdout,
        )

    def test_cli_writes_explicit_inspection_outputs(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            command_dir = _write_bundle(root)
            json_out = root / "reports" / "bundle.json"
            markdown_out = root / "reports" / "bundle.md"
            json_out_path = str(json_out)
            markdown_out_path = str(markdown_out)
            result = subprocess.run(
                [
                    "python3",
                    "-P",
                    str(SCRIPT),
                    str(command_dir),
                    "--json-out",
                    str(json_out),
                    "--markdown-out",
                    str(markdown_out),
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            json_out_exists = json_out.exists()
            markdown_out_exists = markdown_out.exists()
            payload = json.loads(json_out.read_text(encoding="utf-8"))
            markdown = markdown_out.read_text(encoding="utf-8")

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertTrue(json_out_exists)
        self.assertTrue(markdown_out_exists)
        self.assertEqual(payload["action"], "continue_from_accepted")
        self.assertEqual(payload["inspection_json_path"], json_out_path)
        self.assertEqual(payload["inspection_markdown_path"], markdown_out_path)
        self.assertIn("strict_ready: yes", markdown)
        self.assertIn(f"inspection_json_path: {json_out_path}", markdown)

    def test_cli_fails_when_required_artifact_is_missing(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp), missing_comparison_json=True)
            result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

        self.assertEqual(result.returncode, 1)
        payload = json.loads(result.stdout)
        self.assertFalse(payload["bundle_ready"])
        self.assertIn("comparison_json", payload["missing_required"])

    def test_strict_fails_when_declared_script_is_not_executable(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp), non_executable_follow_up=True)
            relaxed = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            strict = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json", "--strict"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

        self.assertEqual(relaxed.returncode, 0, relaxed.stderr)
        payload = json.loads(relaxed.stdout)
        self.assertTrue(payload["bundle_ready"])
        self.assertFalse(payload["strict_ready"])
        self.assertIn("follow_up_script", payload["missing_optional"])
        self.assertEqual(strict.returncode, 1)

    def test_strict_fails_when_runner_wrapper_is_not_executable(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp), non_executable_runner=True)
            relaxed = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            strict = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json", "--strict"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

        self.assertEqual(relaxed.returncode, 0, relaxed.stderr)
        payload = json.loads(relaxed.stdout)
        checks = {item["label"]: item for item in payload["checks"]}
        self.assertTrue(payload["bundle_ready"])
        self.assertFalse(payload["strict_ready"])
        self.assertIn("runner_script", payload["missing_optional"])
        self.assertFalse(checks["runner_script"]["ok"])
        self.assertFalse(payload["runner_wrapper_status"]["executable"])
        self.assertEqual(strict.returncode, 1)

    def test_strict_fails_when_runner_wrapper_is_stale(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            command_dir = _write_bundle(Path(tmp), stale_runner=True)
            relaxed = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            strict = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir), "--json", "--strict"],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            markdown_result = subprocess.run(
                ["python3", "-P", str(SCRIPT), str(command_dir)],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

        self.assertEqual(relaxed.returncode, 0, relaxed.stderr)
        payload = json.loads(relaxed.stdout)
        checks = {item["label"]: item for item in payload["checks"]}
        self.assertTrue(payload["bundle_ready"])
        self.assertFalse(payload["strict_ready"])
        self.assertIn("runner_script", payload["missing_optional"])
        self.assertFalse(checks["runner_script"]["ok"])
        self.assertFalse(payload["runner_wrapper_status"]["contains_runner_command"])
        self.assertFalse(payload["runner_wrapper_status"]["executes_runner_command"])
        self.assertTrue(payload["runner_wrapper_status"]["forwards_arguments"])
        self.assertEqual(strict.returncode, 1)
        self.assertEqual(markdown_result.returncode, 0, markdown_result.stderr)
        self.assertIn(
            "runner_wrapper_contains_runner_command: no",
            markdown_result.stdout,
        )


if __name__ == "__main__":
    unittest.main()
