[package]
name = "st-core"
version = "1.3.2"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "SpiralTorch core (Rust): tensors, autograd, optional MPS backend"
repository = "https://github.com/RyoSpiralArchitect/spiraltorch"

[features]
default = []
mps = ["metal", "objc", "once_cell"]

[dependencies]
ndarray = { version = "0.15", features = ["rayon"] }
once_cell = "1.19"
# metal + objc only when feature mps
metal = { version = "0.27", optional = true }
objc = { version = "0.2", optional = true }

[dev-dependencies]
rand = "0.8"
