[package]
name = "st-core"
version = "1.6.5"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "SpiralTorch core (distributed orchestrators, config, heuristics hooks)"

[features]
default = []
hip = ["st-backend-hip"]

[dependencies]
thiserror = "1"
rand = "0.8"
st-backend-hip = { path = "../st-backend-hip", optional = true }
st-kv = { path = "../st-kv", optional = true, features = ["redis"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
