[package]
name = "st-core"
version = "1.4.6"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "SpiralTorch core: unified heuristics + ops + experimental"

[features]
logic = ["dep:st-logic"]
kdsl = ["dep:st-kdsl"]
kv-redis = ["dep:st-kv/redis"]

[dependencies]
ndarray = "0.15"
rand = "0.8"
thiserror = "1"
st-logic = { path = "../st-logic", optional = true }
st-kdsl  = { path = "../st-kdsl",  optional = true }
st-kv    = { path = "../st-kv",    optional = true }
