
[package]
name = "st-core"
version = "1.5.2"
edition = "2021"
license = "AGPL-3.0-or-later"

[features]
logic = ["dep:st-logic"]
kdsl = ["dep:st-kdsl"]
kv-redis = ["dep:st-kv/redis"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1"
st-logic = { path = "../st-logic", optional = true }
st-kdsl  = { path = "../st-kdsl",  optional = true }
st-kv    = { path = "../st-kv",    optional = true }

# --- v1.5.3 ---
[features]
hip = ["dep:st-backend-hip"]

[dependencies]
st-backend-hip = { path = "../st-backend-hip", optional = true }
