
[package]
name = "st-core"
version = "1.3.52"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "SpiralTorch core (Rust): tensors, ops, and multi-backend execution (CPU/WGPU/MPS/CUDA)."

[lib]
name = "st_core"
path = "src/lib.rs"
crate-type = ["rlib"]

[features]
default = []
wgpu = ["dep:wgpu", "dep:pollster", "dep:once_cell", "dep:bytemuck"]
mps  = ["dep:metal"]
cuda = ["dep:cust"]

[dependencies]
ndarray = "0.15"
thiserror = "1"
once_cell = { version = "1", optional = true }
bytemuck = { version = "1", features=["derive"], optional = true }

wgpu = { version = "0.20", optional = true }
pollster = { version = "0.3", optional = true }
metal = { version = "0.28", optional = true }
cust  = { version = "0.8", features=["nvptx"], optional = true }
