[package]
name = "st-core"
version = "1.3.7"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "SpiralTorch core (Rust): tensors, autograd, CPU/WGPU/MPS/CUDA backends"
repository = "https://github.com/RyoSpiralArchitect/spiraltorch"

[lib]
name = "st_core"
crate-type = ["rlib", "cdylib"]

[features]
default = []
mps = ["metal", "objc"]
wgpu = ["dep:wgpu", "dep:pollster", "dep:bytemuck", "dep:futures-intrusive"]
cuda = ["dep:cust"]

[dependencies]
ndarray = { version = "0.15", features = ["rayon"] }
num-traits = "0.2"
once_cell = "1.19"
thiserror = "1.0"
# MPS
metal = { version = "0.27", optional = true }
objc   = { version = "0.2",  optional = true }
# WGPU
wgpu = { version = "0.19", optional = true }
pollster = { version = "0.3", optional = true }
bytemuck = { version = "1.14", features = ["derive"], optional = true }
futures-intrusive = { version = "0.5", optional = true }
# CUDA
cust = { version = "0.7", optional = true }

pyo3 = { version = "0.21", optional = true, features = ["extension-module", "abi3-py39"] }
