[package]
name = "st-core"
version = "1.3.30"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "SpiralTorch core: tensor + autograd + optional GPU backends"
repository = "https://github.com/RyoSpiralArchitect/spiraltorch"

[lib]
name = "st_core"
path = "src/lib.rs"

[features]
cuda = ["dep:cust"]
cuda = ["dep:cust"]
cuda = ["dep:cust"]
default = []
cuda = ["cust"]
wgpu = ["dep:wgpu", "dep:pollster", "dep:bytemuck"]
mps  = ["dep:metal", "dep:objc"]

[dependencies]
ndarray = "0.15"
thiserror = "1"
once_cell = "1"
bytemuck = { version = "1", optional = true }
pollster = { version = "0.3", optional = true }
wgpu = { version = "0.19", optional = true }
metal = { version = "0.27", optional = true }
objc = { version = "0.2", optional = true }
cust = { version = "0.3", optional = true }

[build-dependencies]
