[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
once_cell = "1"
bytemuck = { version = "1", features = ["derive"] }
dirs = "5"
statrs = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
