[package]
name = "st-core"
version = "1.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "SpiralTorch core (Rust v1.0.1): generalized einsum DP + segment_* + logprod"

[features]
default = []
blas = ["ndarray-linalg", "ndarray/blas"]

[dependencies]
ndarray = { version = "0.15", features = ["rayon"] }
rayon = "1.8"
thiserror = "1.0"
ndarray-linalg = { version = "0.16", optional = true, default-features = false }
