[package]
name = "st-text"
version = "0.1.0"
edition = "2021"
authors = ["Ryo ∴ SpiralArchitect <kishkavsesvit@icloud.com>"]
description = "Resonance-to-language narrators for SpiralTorch"
license = "AGPL-3.0-or-later"

[dependencies]
st-core = { path = "../st-core" }
st-tensor = { path = "../st-tensor" }

[package.metadata.spiraltorch]
copyright = "© 2025 Ryo ∴ SpiralArchitect — All rights reserved"
