[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[project]
name = "spiraltorch-rs"
version = "1.0.1"
requires-python = ">=3.8"
description = "SpiralTorch Rust core — PyTorch-like tensor engine with PyO3 bindings"
readme = { file = "README.md", content-type = "text/markdown" }
license = { text = "MIT OR Apache-2.0" }
keywords = ["tensor", "autograd", "einsum", "segment", "rust", "pyo3", "ndarray", "deep-learning"]
authors = [{ name = "SpiralTorch Contributors" }]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Programming Language :: Rust",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Software Development :: Libraries"
]

[project.urls]
Homepage = "https://github.com/RyoSpiralArchitect/spiraltorch"
Documentation = "https://github.com/RyoSpiralArchitect/spiraltorch#readme"
Repository = "https://github.com/RyoSpiralArchitect/spiraltorch"
Issues = "https://github.com/RyoSpiralArchitect/spiraltorch/issues"
