[package]
authors = ["Ryo ∴ SpiralArchitect <kishkavsesvit@icloud.com>"]
name = "st-logic"
version = "0.2.0"
edition = "2021"

[features]
default = ["soft"]
soft = []

[dependencies]
thiserror = "1"
rand = "0.8"

[package.metadata.spiraltorch]
copyright = "© 2025 Ryo ∴ SpiralArchitect — All rights reserved"
